### ISSUE TITLE
Consul connect: cannot discover the available service correctly.

### ISSUE THREAD

**Issue by hudingchen** [hashicorp/consul#10076]
#### Overview of the Issue

If there is a failure service, it seems the sidecar proxy cannot discover the available service correctly.

#### Reproduction Steps

Steps to reproduce this issue, eg:

client --> web --> payments

1. Start consul server.
<details>
  <summary>consul-single-dc.hcl</summary>

```
data_dir = "/tmp/"
log_level = "DEBUG"
datacenter = "dc1"
server = true
bootstrap_expect = 1
ui = true
bind_addr = "0.0.0.0"
client_addr = "0.0.0.0"
ports {
  http = 8500
  dns = 8600
  server = 8300
  serf_lan = 8301
  serf_wan = 8302
  grpc = 8502
}
connect {
  enabled = true
}
advertise_addr = "10.5.0.2"
```

</details>

2. Start service and sidecar proxy(web).
<details>
  <summary>web.hcl</summary>

```
service {
  name = "web"
  id = "web"
  address = "10.5.0.3"
  port = 9099
  
  connect { 
    sidecar_service {
      port = 20000
      
      check {
        name = "Connect Envoy Sidecar"
        tcp = "10.5.0.3:20000"
        interval ="10s"
      }

      proxy {
        upstreams {
          destination_name = "payments"
          local_bind_address = "127.0.0.1"
          local_bind_port = 9091
        }
      }
    }
  }
}
```

</details>

3.  Start service and sidecar proxy.(payments-1-v1)
<details>
  <summary>payments_1_v1.hcl</summary>

```
service {
  name = "payments"
  id = "payments-1-v1"
  address = "10.5.0.4"
  port = 9090

  tags      = ["v1", "payments-1-v1"]

  check {
    http = "http://10.5.0.4:9090"
    interval = "10s"
  }
  
  connect { 
    sidecar_service {
      port = 20000
      check {
        name = "Connect Envoy Sidecar"
        tcp = "10.5.0.4:20000"
        interval ="10s"
      }
    }
  }
}
```

</details>

4.  Start service and sidecar proxy.(payments-2-v1)
<details>
  <summary>payments_2_v1.hcl</summary>

```
service {
  name = "payments"
  id = "payments-2-v1"
  address = "10.5.0.5"
  port = 9090

  tags      = ["v1", "payments-2-v1"]

  check {
    http = "http://10.5.0.5:9090"
    interval = "10s"
  }

  connect { 
    sidecar_service {
      port = 20000
      
      check {
        name = "Connect Envoy Sidecar"
        tcp = "10.5.0.5:20000"
        interval ="10s"
      }
    }  
  }
}
```

</details>

5. Run `curl 127.0.0.1:8080/web`, will randomly return payments-1-v1 or payments-2-v1.
<details>
  <summary>payments-1-v1 result</summary>

```
{
  "name": "web",
  "uri": "/web",
  "type": "HTTP",
  "ip_addresses": [
    "10.5.0.3"
  ],
  "start_time": "2021-04-20T23:13:42.932185",
  "end_time": "2021-04-20T23:13:42.936849",
  "duration": "4.663425ms",
  "body": "Hello World",
  "upstream_calls": [
    {
      "name": "payments-1-v1",
      "uri": "http://localhost:9091",
      "type": "HTTP",
      "ip_addresses": [
        "10.5.0.4"
      ],
      "start_time": "2021-04-20T23:13:42.936261",
      "end_time": "2021-04-20T23:13:42.936344",
      "duration": "83.501µs",
      "body": "PAYMENTS 1 V1",
      "code": 200
    }
  ],
  "code": 200
}
```

</details>

<details>
  <summary>payments-2-v1 result</summary>

```
{
  "name": "web",
  "uri": "/web",
  "type": "HTTP",
  "ip_addresses": [
    "10.5.0.3"
  ],
  "start_time": "2021-04-20T23:57:03.698306",
  "end_time": "2021-04-20T23:57:03.705480",
  "duration": "7.173656ms",
  "body": "Hello World",
  "upstream_calls": [
    {
      "name": "payments-2-v1",
      "uri": "http://localhost:9091",
      "type": "HTTP",
      "ip_addresses": [
        "10.5.0.5"
      ],
      "start_time": "2021-04-20T23:57:03.704401",
      "end_time": "2021-04-20T23:57:03.704700",
      "duration": "287.554µs",
      "body": "PAYMENTS 2 V1",
      "code": 200
    }
  ],
  "code": 200
}
```

</details>

6. Stop payments-1-v1 service.
```
docker-compose stop payments-1-v1
```
7. Run `curl 127.0.0.1:8080/web`, it will randomly return an error.
<details>
  <summary>error result</summary>

```
{
  "name": "web",
  "uri": "/web",
  "type": "HTTP",
  "ip_addresses": [
    "10.5.0.3"
  ],
  "start_time": "2021-04-20T13:56:47.630945",
  "end_time": "2021-04-20T13:56:47.635042",
  "duration": "4.09659ms",
  "upstream_calls": [
    {
      "uri": "http://localhost:9091",
      "code": -1,
      "error": "Error communicating with upstream service: Get http://localhost:9091/web: read tcp 127.0.0.1:49486-\u003e127.0.0.1:9091: read: connection reset by peer"
    }
  ],
  "code": 500
}
```

</details>

web_proxy envoy debug log:
```
web_proxy              | [2021-04-20 23:31:23.464][69][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:242] [C33] new tcp proxy session
web_proxy              | [2021-04-20 23:31:23.464][69][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:389] [C33] Creating connection to cluster payments.default.dc1.internal.501621d3-5e87-8e59-4183-4e9ae954b75b.consul
web_proxy              | [2021-04-20 23:31:23.464][69][debug][pool] [source/common/tcp/original_conn_pool.cc:98] creating a new connection
web_proxy              | [2021-04-20 23:31:23.464][69][debug][pool] [source/common/tcp/original_conn_pool.cc:383] [C34] connecting
web_proxy              | [2021-04-20 23:31:23.465][69][debug][connection] [source/common/network/connection_impl.cc:755] [C34] connecting to 10.5.0.4:20000   <----- payments-1-v1
```

I refer to the following documents:
https://www.consul.io/docs/connect/proxies/integrate#service-discovery

```
Proxies can use Consul's service discovery API /v1/health/connect/:service_id to return all available, Connect-capable endpoints for a given service. 
```

I thought web_proxy should discover `payments-2-v1` service, if `payments-1-v1` service is not available.
But, it seems web_proxy discover the `payments` sidecar , not the `payments` service.
Is my understanding correct?

### Operating system and Environment details

OS: Centos 7.7
docker: 19.03.5
docker-compose: 1.25.0
consul: 1.9.1
envoy: 1.16

<details>
  <summary>docker-compose.yml</summary>

```
version: "3.3"
services:

  consul_server_1:
    image: ${CONSUL_IMAGE}
    container_name: consul_server_1
    command: ["consul","agent", "-server", "-bootstrap", "-config-file=/config/consul-single-dc.hcl","-config-dir=/config"]
    volumes:
      - "./consul_config:/config"
    ports:
      - "8500:8500"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  web_proxy:
    image: ${CONSUL_ENVOY_IMAGE}
    container_name: web_proxy
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/web.hcl
    volumes:
      - "./web_consul_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "web", "--", "-l", "debug"]
    ports:
      - "8080:9099"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  web:
    image: ${PROXY_SERVER}/nicholasjackson/fake-service:v0.7.8
    container_name: web
    environment:
      LISTEN_ADDR: 0.0.0.0:9099
      UPSTREAM_URIS: http://localhost:9091
      NAME: web
      MESSAGE: "Hello World"
      HTTP_CLIENT_KEEP_ALIVES: "false"
    network_mode: "service:web_proxy"

  payments_1_proxy_v1:
    image: ${CONSUL_ENVOY_IMAGE}
    container_name: payments_1_proxy_v1
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/payments_1_v1.hcl
    volumes:
      - "./payments_1_consul_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "payments-1-v1", "--", "-l", "debug"]
    ports:
      - "9001:9090"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  payments_1_v1:
    image: ${PROXY_SERVER}/nicholasjackson/fake-service:v0.7.8
    container_name: payments_1_v1
    environment:
      NAME: payments-1-v1
      MESSAGE: "PAYMENTS 1 V1"
    network_mode: "service:payments_1_proxy_v1"

  payments_2_proxy_v1:
    image: ${CONSUL_ENVOY_IMAGE}
    container_name: payments_2_proxy_v1
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/payments_2_v1.hcl
    volumes:
      - "./payments_2_consul_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "payments-2-v1", "--", "-l", "debug"]
    ports:
      - "9002:9090"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  payments_2_v1:
    image: ${PROXY_SERVER}/nicholasjackson/fake-service:v0.7.8
    container_name: payments_2_v1
    environment:
      NAME: payments-2-v1
      MESSAGE: "PAYMENTS 2 V1"
    network_mode: "service:payments_2_proxy_v1"

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
```

</details>
