### ISSUE TITLE
Consul Service Mesh - Service resolver not working with connectTimeout parameter 

### ISSUE THREAD

**Issue by nikhil-cldcvr** [hashicorp/consul#10137]
I am trying to deploy the service resolver kind in k8s by referring the doc. 
https://www.consul.io/docs/connect/config-entries/service-resolver#datacenter-failover 
Consul Version: 1.9.5-ent

But i am getting the failure while applying the manifest. Getting the below error.

cat recommendation-svc-resolver.yaml
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: recommendationservice
spec:
  connectTimeout: 2s
  defaultSubset: ''
  subsets:
     'v1':
       filter: 'Service.Meta.version == v1'
     'v2':
       filter: 'Service.Meta.version == v2'
```

```
 k apply -f recommendation-svc-resolver.yaml
Error from server: error when creating "recommendation-svc-resolver.yaml": admission webhook "mutate-serviceresolver.consul.hashicorp.com" denied the request: v1alpha1.ServiceResolver.Spec: v1alpha1.ServiceResolverSpec.ConnectTimeout: readUint64: unexpected character: �, error found in #10 byte of ...|Timeout":"2s","defau|..., bigger context ...|,"namespace":"default"},"spec":{"connectTimeout":"2s","defaultSubset":"","subsets":{"v1":{"filter":"|...

```
