### ISSUE TITLE
L7 Deny intentions not working as expected

### ISSUE THREAD

**Issue by vineethgopinadhan** [hashicorp/consul#10753]
#### Overview of the Issue

This is a continuation of the issue (https://github.com/hashicorp/consul/issues/10536) experienced in L7 intentions. Tried with updated versions . 

Tried with   **hashicorp/consul-enterprise:1.10.1-ent**   version  using **v0.32.1**  helm chart.  

#### Reproduction Steps

Please find below details.

1.  Helm Config used -  
[config-dc-1.txt](https://github.com/hashicorp/consul/files/6903097/config-dc-1.txt)
2. Service defaults created  with cr 
```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: service-one
  namespace: consul-connect
spec:
  protocol: http
```
3. Intention
```bash
curl  -H "X-Consul-Token: ${CONSUL_TOKEN}" -H "X-Consul-Namespace: consul-connect" -k  ${CONSUL_HTTP_ADDR}/v1/connect/intentions?filter=SourceName==\"curl-client-tp\"
```
```json
[
    {
        "SourceNS": "consul-connect",
        "SourceName": "curl-client-tp",
        "DestinationNS": "consul-connect",
        "DestinationName": "service-one",
        "SourceType": "consul",
        "Permissions": [
            {
                "Action": "deny",
                "HTTP": {
                    "PathExact": "/health"
                }
            }
        ],
        "Precedence": 9,
        "CreateIndex": 845,
        "ModifyIndex": 2110
    }
]
```
Current Test Results
---------------------
All the calls from **curl-client-tp**   to   **service-one** are denied now.   
```bash
sh-4.2$ curl service-one
RBAC: access denied
sh-4.2$ 
sh-4.2$ curl service-one/health   
RBAC: access denied
sh-4.2$ 
sh-4.2$ curl service-one/health/v1
RBAC: access denied
sh-4.2$ 
```

Expected Result
-----------------
-  Only **/health**  to be denied
-  **/**  and **/health/v1**   should be allowed. 

Please let me know if I am missing any configuration. Thanks.

**Comment by blake** [comment]
Hi @vineethgopinadhan,

The [ACL default policy](https://www.consul.io/docs/agent/options#acl_default_policy) is set to `deny` when ACLs are enabled in the Helm chart.

This affects the evaluation of intentions – as mentioned here https://www.consul.io/docs/connect/intentions – wherein there is an implicit deny or allow rule that exists after the specified rules in your rule set.

> The default intention behavior is defined by the default ACL policy. If the default ACL policy is "allow all", then all Connect connections are allowed by default. If the default ACL policy is "deny all", then all Connect connections or requests are denied by default.

The ruleset being rendered is effectively this:

* Deny requests from curl-client-tp to service-one for the /health endpoint.
* Deny all requests

You must create an explicit allow rule to grant access to paths other than /health. For example:

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: service-one
  namespace: consul-connect
spec:
  destination:
    name: service-one
  sources:
    - name: curl-client-tp
      permissions:
        - action: deny
          http:
            pathExact: /health
    - name: curl-client-tp
      permissions:
        - action: allow
          http:
            # This will allow access to all other paths which are not previously denied.
            pathPrefix: /
    # NOTE: a default catch-all based on the default ACL policy will apply to
    # unmatched connections and requests. Typically this will be DENY.
```

Please try this configuration and let me know whether it resolve the policy issue. Thanks.
