### ISSUE TITLE
consul connect redirect-traffic

### ISSUE THREAD

**Issue by rola0411** [hashicorp/consul#11038]
docker exec -it ead27e00dbe5 consul connect redirect-traffic \
-proxy-id="demo-two-0-sidecar-proxy" \
-proxy-uid="???" \

I don`t understand this  proxy-uid  or how to do?

I install dnsmasq  to  consul dns: 8600.   config content is : server=/#/192.168.103.238#8600

my case is ：  curl demo-one/demo ，   and demo-one will access demo-two by transparent_proxy

in the VM , I want springboot project :  demo-one ----> demo-two 

```yaml
curl -k https://127.0.0.1:8501/v1/agent/service/register \
--header "X-Consul-Token: 98e4ede4-271b-383b-94b7-c085137188fe" \
--request PUT \
--data '{
    "id": "demo-one-0",
    "name": "demo-one",
    "port": 8081,
    "connect": {
        "sidecar_service": {
            "proxy": {
                "mode": "transparent",
                "transparent_proxy": {
                    "OutboundListenerPort": 15001,
                    "DialedDirectly": true
                }
            }
        }
    },
    "check": {
        "http": "http://192.168.103.238:8081/health",
        "method": "GET",
        "interval": "1s",
        "timeout": "1s"
    }
}'

```
