### ISSUE TITLE
Envoy proxy doesn't start proxy on start

### ISSUE THREAD

**Issue by ghost** [hashicorp/consul#11410]
I have a consul architecture based on :
- 3 servers running on VMs
- 1 client per kubernetes node ( GKE )

So I used the chart helm to deploy the clients + the connect injector. Everything went well during deployment and injection. I don't have any feedback errors.

On the other hand, when I look at the status of my service on Consul it appears unhealthy because of the Proxy Public Listener health check.
This one indicates a refused connection on port 20000 of my pod.

So I went to launch a `netstat -tulpn | grep LISTEN` on my pod and I see the following result:

![](https://user-images.githubusercontent.com/76174192/138718955-1bf9023e-1962-4784-bdbb-19b236bd48ec.png)

Indeed nothing is launched on the port 20000. When I look at the send logs, no problem is reported.

Has anyone already experienced this problem, and if so, do you have any idea what could be the problem?

Here is the configuration of my service: 

```yaml
podAnnotations:
  consul.hashicorp.com/connect-inject: "true"
  consul.hashicorp.com/connect-service: "k8s_nginx"
  consul.hashicorp.com/envoy-extra-args: "--log-level debug --disable-hot-restart"
```
