### ISSUE TITLE
Unable to start Consul Docker container - node-id permission denied

### ISSUE THREAD

**Issue by chris-aeviator** [hashicorp/consul#11459]
```
badger_1   | ==> failed to setup node ID: open /consul/data/node-id: permission denied
```

```
version: '3'

services:
  badger:
    image: consul:1.8.5
    volumes:
        - ./consul:/consul
    command: agent -server --data-dir=/consul/data -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
```

```
ls -la ./consul/data

drwxrwxrwx 4 root  root  4096 Oct 31 13:15 .
drwxrwxrwx 4 root  root  4096 Oct 31 13:07 ..
-rwxrwxrwx 1 korny korny  394 Oct 31 13:07 checkpoint-signature
-rwxrwxrwx 1 korny korny    0 Oct 31 13:15 node-id
drwxrwxrwx 3 korny korny 4096 Oct 31 13:07 raft
drwxrwxrwx 2 korny korny 4096 Oct 31 13:07 serf
```

what's going on here? Obviously no permission issue possible
