### ISSUE TITLE
Outlier detection not working with transparent proxy

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#11570]
#### Overview of the Issue

When transparent proxy mode is enabled Envoy appears to not be counting failed requests. This results in outlier detection never triggering.

#### Reproduction Steps

Install consul-k8s 0.36.0 on kube using:

```yaml
global:
  name: consul
server:
  replicas: 1
connectInject:
  enabled: true
controller:
  enabled: true
```

Create two services: frontend and backend. Backend is configured to always respond with 500's. Frontend will have two pods, one will use tproxy and one will use explicit upstreams. Also configure the protocol as http:

<details>

<summary>workloads.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
        - name: backend
          image: nicholasjackson/fake-service:v0.21.0
          env:
            - name: LISTEN_ADDR
              value: "0.0.0.0:7000"
            - name: NAME
              value: "backend"
            - name: ERROR_RATE
              value: "1"
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-no-tproxy
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/transparent-proxy": "false"
        "consul.hashicorp.com/connect-service-upstreams": "backend:1234"
    spec:
      containers:
        - name: frontend
          image: nicholasjackson/fake-service:v0.21.0
          env:
            - name: "LISTEN_ADDR"
              value: "0.0.0.0:6060"
            - name: NAME
              value: "frontend"
            - name: UPSTREAM_URIS
              value: "http://localhost:1234"
          ports:
            - containerPort: 6060
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-tproxy
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
        - name: frontend
          image: nicholasjackson/fake-service:v0.21.0
          env:
            - name: "LISTEN_ADDR"
              value: "0.0.0.0:6060"
            - name: NAME
              value: "frontend"
            - name: UPSTREAM_URIS
              value: "http://backend"
          ports:
            - containerPort: 6060
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  config:
    protocol: http

```

</details>

```
kubectl apply -f workloads.yaml
```

Exec into the tproxy frontend pod:

```
kubectl exec -it  frontend-tproxy-684cf7c489-4f2cp -- sh
```

**NOTE:** You can't use `kubectl exec deploy/frontend` because that might select the tproxy pod.

`curl` backend 6 times:

```
for i in 1 2 3 4 5 6; do curl -sS http://backend; done
```

The 6th request should have triggered the outlier detection since it's set by default to 5 failures but it doesn't trigger it. 

Look at the clusters output:

```
curl 'localhost:19000/clusters?format=json'
```

```json
  {
   "name": "backend.default.dc1.internal.b5b04f5b-e311-cb02-f3a7-b2cef86e536e.consul",
   "added_via_api": true,
   "host_statuses": [
    {
     "address": {
      "socket_address": {
       "address": "10.32.9.41",
       "port_value": 20000
      }
     },
     "stats": [
      {
       "name": "cx_connect_fail"
      },
      {
       "value": "7",
       "name": "cx_total"
      },
      {
       "name": "rq_error"
      },
      {
       "name": "rq_success"
      },
      {
       "name": "rq_timeout"
      },
      {
       "value": "7",
       "name": "rq_total"
      },
      {
       "type": "GAUGE",
       "name": "cx_active"
      },
      {
       "type": "GAUGE",
       "name": "rq_active"
      }
     ],
     "health_status": {
      "eds_health_status": "HEALTHY"
     },
     "weight": 1,
     "locality": {}
    }
   ],
   "circuit_breakers": {
    "thresholds": [
     {
      "max_connections": 1024,
      "max_pending_requests": 1024,
      "max_requests": 1024,
      "max_retries": 3
     },
     {
      "priority": "HIGH",
      "max_connections": 1024,
      "max_pending_requests": 1024,
      "max_requests": 1024,
      "max_retries": 3
     }
    ]
   },
   "observability_name": "backend.default.dc1.internal.b5b04f5b-e311-cb02-f3a7-b2cef86e536e.consul"
  }
 ]
}
```

You'll see that `health_status` has no outlier detection triggered **and** `rq_error` is empty.

Now perform the same test with the no-tproxy pod, but this time `curl localhost:1234`.

You'll see that you get `no health upstreams` on the 6th request and the cluster output is;

```json
  {
   "name": "backend.default.dc1.internal.b5b04f5b-e311-cb02-f3a7-b2cef86e536e.consul",
   "added_via_api": true,
   "host_statuses": [
    {
     "address": {
      "socket_address": {
       "address": "10.32.9.41",
       "port_value": 20000
      }
     },
     "stats": [
      {
       "name": "cx_connect_fail"
      },
      {
       "value": "1",
       "name": "cx_total"
      },
      {
       "value": "5",
       "name": "rq_error"
      },
      {
       "name": "rq_success"
      },
      {
       "name": "rq_timeout"
      },
      {
       "value": "5",
       "name": "rq_total"
      },
      {
       "type": "GAUGE",
       "name": "cx_active"
      },
      {
       "type": "GAUGE",
       "name": "rq_active"
      }
     ],
     "health_status": {
      "failed_outlier_check": true,
      "eds_health_status": "HEALTHY"
     },
     "weight": 1,
     "locality": {}
    }
   ],
   "circuit_breakers": {
    "thresholds": [
     {
      "max_connections": 1024,
      "max_pending_requests": 1024,
      "max_requests": 1024,
      "max_retries": 3
     },
     {
      "priority": "HIGH",
      "max_connections": 1024,
      "max_pending_requests": 1024,
      "max_requests": 1024,
      "max_retries": 3
     }
    ]
   },
   "observability_name": "backend.default.dc1.internal.b5b04f5b-e311-cb02-f3a7-b2cef86e536e.consul"
  },
```

### Consul info for both Client and Server

Consul v1.10.3

**Comment by lkysow** [comment]
Retry policy is also not working, for example:

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: backend
spec:
  routes:
    - destination:
        numRetries: 5
        retryOnStatusCodes: [500, 503]
```

Workaround for now is to not use tproxy and use explicit upstreams via:

```
        consul.hashicorp.com/connect-service-upstreams: backend:7070
        consul.hashicorp.com/transparent-proxy: "false"
```
