### ISSUE TITLE
500 Error on ConfigEntry.ResolveServiceConfig

### ISSUE THREAD

**Issue by hamishforbes** [hashicorp/consul#11637]
#### Overview of the Issue

I'm intermittently getting an error in the consul-k8s connect inject controller when registering sidecar proxies.
I've not managed to trace the error beyond the local agent.
Consul server nodes in the local DC and the primary DC don't log any errors that i can find (even using `consul monitor -log-level trace`)

#### Reproduction Steps

I don't know, it must be related to `service-defaults` config entries somehow but i've tried every combination of setting values, not-setting, present and not-present for the client and server services, but nothing is consistently producing the error.

Kubernetes manifests and example TF for config entries
https://gist.github.com/hamishforbes/39aeecc466a3b314a7d628f07f005948

### Consul info for both Client and Server
1.10.4 on client and server
0.37.0 on consul-k8s

### Log Fragments

consul-consul-connect-injector-webhook-deployment
```
2021-11-24T03:18:12.107Z	ERROR	controller.endpoints	Reconciler error	{"reconciler group": "", "reconciler kind": "Endpoints", "name": "client", "namespace": "test", "error": "1 error occurred:\n\t* Unexpected response code: 500 (could not retrieve initial service_defaults config for service \"client-7bc7c4b89d-xfhmz-client-sidecar-proxy\": rpc error making call: reflect: call of reflect.Value.Type on zero Value)\n\n"}
```

consul agent
```
2021-11-24T03:10:35.051Z [ERROR] agent.client: RPC failed to server: method=ConfigEntry.ResolveServiceConfig server=10.20.3.83:8300 error="rpc error making call: reflect: call of reflect.Value.Type on zero Value"
```

service-defaults for client
```
> consul config read -kind service-defaults -name client
{
    "Kind": "service-defaults",
    "Name": "client",
    "TransparentProxy": {},
    "MeshGateway": {},
    "Expose": {},
    "UpstreamConfig": {
        "Defaults": {
            "Limits": {
                "MaxConnections": 2000,
                "MaxPendingRequests": null,
                "MaxConcurrentRequests": null
            },
            "MeshGateway": {}
        }
    },
    "CreateIndex": 464141018,
    "ModifyIndex": 464149878
}
```

**Comment by Amier3** [comment]
@hamishforbes 

Thanks for letting us know about this weird behavior. Just letting you know that we didn't forget about this, and i'm actively trying to reproduce this behavior so we can drill down the problem 👍

**Comment by lkysow** [comment]
@hamishforbes I've reproduced this myself. As a workaround, I've found that setting the values for all the limits explicitly works. The Envoy defaults are 1024 so you could do:

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: frontend
spec:
  protocol: http
  upstreamConfig:
    defaults:
      limits:
        maxConnections: 2
        maxPendingRequests: 1024
        maxConcurrentRequests: 1024
```

**Comment by lkysow** [comment]
Note: this is not specific to Kubernetes.

```
cat test.hcl
```

```hcl
kind = "service-defaults"
name = "test"
protocol = "http"
upstreamConfig {
  defaults {
    limits {
      maxConnections = 2
    }
  }
}
```

```json
consul config read -kind service-defaults -name test
{
    "Kind": "service-defaults",
    "Name": "test",
    "Protocol": "http",
    "TransparentProxy": {},
    "MeshGateway": {},
    "Expose": {},
    "UpstreamConfig": {
        "Defaults": {
            "Limits": {
                "MaxConnections": 2,
                "MaxPendingRequests": null,
                "MaxConcurrentRequests": null
            },
            "MeshGateway": {}
        }
    },
    "CreateIndex": 3802,
    "ModifyIndex": 3802
}
```

**Comment by kisunji** [comment]
@lkysow Do you have any reproduction steps handy?
I haven't touched consul-k8s but would love to get some exposure while debugging here

**Comment by lkysow** [comment]
I couldn't repro without Kubernetes but I don't think it's Kube specifically. Here's the repro, feel free to ping me.

Install with this values.yaml:

```
connectInject:
  enabled: true
controller:
  enabled: true
global:
  name: consul
server:
  replicas: 1
```

Once up, `kubectl apply -f` this file:

```
# service-defaults.yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: static-client
spec:
  protocol: http
  upstreamConfig:
    defaults:
      limits:
        maxConnections: 2
```

Now apply this service yaml:

```yaml
apiVersion: v1
kind: Service
metadata:
  # This name will be the service name in Consul.
  name: static-client
spec:
  selector:
    app: static-client
  ports:
    - port: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-client
  template:
    metadata:
      name: static-client
      labels:
        app: static-client
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
        - name: static-client
          image: curlimages/curl:latest
          # Just spin & wait forever, we'll use `kubectl exec` to demo
          command: ['/bin/sh', '-c', '--']
          args: ['while true; do sleep 30; done;']
      # If ACLs are enabled, the serviceAccountName must match the Consul service name.
      serviceAccountName: static-client
```

If you look in the logs of one of the `consul-connect-injector-webhook-deployment-.....` pods you'll see the errors.
