### ISSUE TITLE
Consul healthchecks with TLS - x509: certificate signed by unknown authority 

### ISSUE THREAD

**Issue by nazario29** [hashicorp/consul#11745]
Just started to use consul and recently decided to get the services endpoints to use SSL, and I'm having an issue with the healthchecks to https endpoints - returning `Get "https://myserviceurl": x509: certificate signed by unknown authority`. On Docker Desktop I'm running a docker-compose with a couple of dotnet applications and consul configured as below:
```
  consul:
    image: consul
    container_name: consul
    hostname: consul
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8501:8501'
      - '8600:8600'
      - '8600:8600/udp'
    volumes:
      - .\Certs:/usr/share/ca-certificates
      - .\consul:/consul/config
```
I know we can pass the `skipTlsverify ` flag to workaround this issue but what I'm finding odd is that some healthchecks are actually working and for each application one certificate was generated from the same CA root certificate using this powershell commands:
```
New-SelfSignedCertificate -DnsName "$Hostname" -Signer $RootCA -KeyLength 2048 `
        -KeyAlgorithm 'RSA' -HashAlgorithm 'SHA256' -KeyExportPolicy Exportable -NotAfter $((Get-Date).AddYears(10)) `
        -CertStoreLocation 'Cert:\LocalMachine\My' -FriendlyName "$Hostname"
```

I can confirm that the TLS verification is working fine when running consul outside of docker - on my particular case on a windows VM.
So my question is around the requirements that consul have to actually verify TLS communication on Docker?
