### ISSUE TITLE
Envoy Traffic Filter with Terminating Gateway doesn't seem to be populated correctly

### ISSUE THREAD

**Issue by remiphilippe** [hashicorp/consul#12116]
Hello,
Trying to configure the terminating gateways and I'm running into a weird issue. This is happening on both 1.11.1 and 1.11.2 (I just tested 1.10.7, same issue), so I'm guessing it's a configuration issue, but can't find what's wrong!

Connections get dropped in the source envoy:
```
[2022-01-19 06:20:47.385][21][debug][filter] [source/extensions/filters/listener/original_dst/original_dst.cc:20] original_dst: new connection accepted
[2022-01-19 06:20:47.385][21][debug][conn_handler] [source/server/active_stream_listener_base.cc:34] closing connection from 10.1.3.69:55488: no matching filter chain found
```

and the connection is reset.

Services are registering correctly in consul with the correct IPs, they get attached properly to the terminating gateway, but when the gateway renders the envoy filters:
```
{
    "filter_chain_match": {
        "prefix_ranges": [{
            "address_prefix": "240.0.0.15",
            "prefix_len": 32
        }]
    },
    "filters": [{
        "name": "envoy.filters.network.tcp_proxy",
        "typed_config": {
            "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
            "stat_prefix": "upstream.mongodb.default.default.dev01",
            "cluster": "mongodb.default.dev01.internal.38e65197-9c61-33a2-52cc-b31b1a0a4dcd.consul"
        }
    }]
}
```

The IP address is never there (for this test I was using 8.8.8.8, but it does the same for every IP address).
I've tried by sourcing the service from a k8s service or by configuration the behavior is always the same.

This is the service config I pushed:
```
{
    "Node": "node01",
    "Address": "8.8.8.8",
    "NodeMeta": {
      "external-node": "true",
      "external-probe": "true"
    },
    "Service": {
      "ID": "mongodb1",
      "Service": "mongodb",
      "Port": 27017
    }
  }
```

And the resulting config:
```
[
  {
    "ID": "",
    "Node": "node01",
    "Address": "8.8.8.8",
    "Datacenter": "dev01",
    "TaggedAddresses": null,
    "NodeMeta": {
      "external-node": "true",
      "external-probe": "true"
    },
    "ServiceKind": "",
    "ServiceID": "mongodb1",
    "ServiceName": "mongodb",
    "ServiceTags": [],
    "ServiceAddress": "",
    "ServiceWeights": {
      "Passing": 1,
      "Warning": 1
    },
    "ServiceMeta": {},
    "ServicePort": 27017,
    "ServiceSocketPath": "",
    "ServiceEnableTagOverride": false,
    "ServiceProxy": {
      "Mode": "",
      "MeshGateway": {},
      "Expose": {}
    },
    "ServiceConnect": {},
    "CreateIndex": 4487,
    "ModifyIndex": 4487
  }
]
```

This is the configs I'm using
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  config:
    protocol: grpc
    envoy_dns_discovery_type: LOGICAL_DNS
    envoy_gateway_bind_tagged_addresses: false
  transparentProxy:
    dialedDirectly: false
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: local-gateway
spec:
  services:
    - name: mongodb
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: allow-mongo
spec:
  destination:
    name: 'mongodb'
  sources:
    - name: 'test-src'
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: mongodb
spec:
  protocol: 'http'
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: Mesh
metadata:
  name: mesh
spec:
  transparentProxy:
    meshDestinationsOnly: true
```

Deployment was done with Helm Chat v0.39:
```
global:
  datacenter: dev01
  name: "consul"
  image: "hashicorp/consul:1.11.2"
  imageEnvoy: "envoyproxy/envoy:v1.20.0"
  metrics:
    enabled: true
    enableAgentMetrics: false
    agentMetricsRetentionTime: '1m'
  tls:
    enabled: true
    enableAutoEncrypt: true
    httpsOnly: true
  acls:
    manageSystemACLs: true
ui:
  service:
    enabled: enabled
    type: 'ClusterIP'
  metrics:
    enabled: true
    provider: "prometheus"
    baseURL: "http://prometheus-server.default.svc.cluster.local"
  ingress:
    enabled: true
    annotations: |
      'nginx.ingress.kubernetes.io/backend-protocol': "HTTPS"
      'kubernetes.io/ingress.class': "nginx"
    hosts:
      - host: consul.bla.local
        paths:
          - /
server:
  affinity: null
  replicas: 1
  connect: true
client:
  enabled: true
  grpc: true
controller:
  enabled: true
terminatingGateways:
  enabled: true
  defaults:
    replicas: 1
    affinity: 'null'
  gateways:
    - name: local-gateway
syncCatalog:
  enabled: true
  default: false
  toK8S: false
  addK8SNamespaceSuffix: false
connectInject:
  enabled: true
  default: false
  replicas: 1
  transparentProxy:
    defaultEnabled: true
  metrics:
    defaultEnableMerging: false
```

Service to Service is working fine though (except for this multicast address, not sure where it comes from but it doesn't impact service):
```
{
    "filter_chain_match": {
        "prefix_ranges": [{
                "address_prefix": "10.96.156.48",
                "prefix_len": 32
            },
            {
                "address_prefix": "240.0.0.7",
                "prefix_len": 32
            }
        ]
    },
    "filters": [{
        "name": "envoy.filters.network.tcp_proxy",
        "typed_config": {
            "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
            "stat_prefix": "upstream.bla.default.default.dev01",
            "cluster": "bla.default.dev01.internal.38e65197-9c61-33a2-52cc-b31b1a0a4dcd.consul"
        }
    }]
}
```

**Comment by blake** [comment]
Hi @remiphilippe,

Until recently, Consul did not supported using transparent proxy to route to services which are exposed through a terminating gateway. This functionality was added in Consul 1.11.2 with #12049.

In environments where you're running a version of Consul _older_ than to 1.11.2, you would need to access the external service through an explicit upstream configured using the [`consul.hashicorp.com/connect-service-upstreams`](https://www.consul.io/docs/k8s/connect#consul-hashicorp-com-connect-service-upstreams) annotation on your pod/deployment. For example:

```yaml
annotations:
  consul.hashicorp.com/connect-service-upstreams: "mongodb:27017"
```

However, since you recently upgraded to Consul 1.11.2, you can now connect to an external service using transparent proxy if you access it using the virtual IP assigned by Consul. (VIP allocation was added in Consul 1.11.0.)

You can find this IP by querying Consul's DNS server for `<service>.virtual.consul`, e.g., `mongodb.virtual.consul`. (See [Service Virtual IP Lookups](https://www.consul.io/docs/discovery/dns#service-virtual-ip-lookups) for more info.)

If you have not already done so, follow the instructions at [Consul DNS on Kubernetes](https://www.consul.io/docs/k8s/dns) to configure your cluster to forward DNS queries for the `.consul` TLD to Consul, or use the Helm chart's [`dns`](https://www.consul.io/docs/k8s/helm#dns) parameter to enable automatic redirection of DNS queries to Consul for Connect-enabled services.

```yaml
dns:
  enabled: true
  enableRedirection: true
``` 

> Service to Service is working fine though (except for this multicast address, not sure where it comes from but it doesn't impact service):

The "multicast" address is actually an IP from the CIDR `240.0.0.0/4`, formerly known as Class E address space. Consul allocates each service in the mesh a globally unique virtual IP from this CIDR block. That is why you are seeing these IPs in the filter chains for other services fronted by their own proxy, or a terminating gateway.

I hope this info is helpful. Let me know if you have any other questions.

**Comment by remiphilippe** [comment]
Thanks @blake that's super useful! I was using a doc in reference that wasn't mentioning the virtual stuff (yet)
I've tried with the virtual.consul, but still no luck.

With mesh only disabled, using the kube service
```
root@test-deployment-d77b566ff-mhj7k:/go# curl -v mongodb.default.svc.cluster.local:27017*   Trying 10.103.54.21:27017...
* Connected to mongodb.default.svc.cluster.local (10.103.54.21) port 27017 (#0)
> GET / HTTP/1.1
> Host: mongodb.default.svc.cluster.local:27017
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Connection: close
< Content-Type: text/plain
< Content-Length: 85
< 
It looks like you are trying to access MongoDB over HTTP on the native driver port.
* Closing connection 0
root@test-deployment-d77b566ff-mhj7k:/go# curl -v mongodb.default.svc:27017
*   Trying 10.103.54.21:27017...
* Connected to mongodb.default.svc (10.103.54.21) port 27017 (#0)
> GET / HTTP/1.1
> Host: mongodb.default.svc:27017
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Connection: close
< Content-Type: text/plain
< Content-Length: 85
< 
It looks like you are trying to access MongoDB over HTTP on the native driver port.
* Closing connection 0
```
with the virtual.consul address
```
root@test-deployment-d77b566ff-mhj7k:/go# curl -v mongodb.virtual.consul:27017
*   Trying 240.0.0.14:27017...
* Connected to mongodb.virtual.consul (240.0.0.14) port 27017 (#0)
> GET / HTTP/1.1
> Host: mongodb.virtual.consul:27017
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host mongodb.virtual.consul left intact
curl: (52) Empty reply from server
root@test-deployment-d77b566ff-mhj7k:/go#
```


error is "better" now though, it seems that the terminating gateway is reseting the connection:
```
[2022-01-19 15:48:33.710][17][debug][conn_handler] [source/server/active_tcp_listener.cc:140] [C165] new connection from 10.1.3.155:53690
[2022-01-19 15:48:33.710][17][debug][connection] [source/common/network/connection_impl.cc:672] [C166] connected
[2022-01-19 15:48:33.710][17][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:217] [C166] TLS error: 33554536:system library:OPENSSL_internal:Connection reset by peer
[2022-01-19 15:48:33.710][17][debug][connection] [source/common/network/connection_impl.cc:249] [C166] closing socket: 0
[2022-01-19 15:48:33.710][17][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:217] [C166] TLS error: 33554536:system library:OPENSSL_internal:Connection reset by peer
[2022-01-19 15:48:33.710][17][debug][pool] [source/common/conn_pool/conn_pool_base.cc:422] [C166] client disconnected, failure reason: 
[2022-01-19 15:48:33.710][17][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:338] [C165] Creating connection to cluster mongodb.default.dev01.internal.11c4a5d5-d6c7-fc12-7f78-362bc046db7f.consul
[2022-01-19 15:48:33.710][17][debug][connection] [source/common/network/connection_impl.cc:138] [C165] closing data_to_write=0 type=1
[2022-01-19 15:48:33.710][17][debug][connection] [source/common/network/connection_impl.cc:249] [C165] closing socket: 1
```

I don't see any logs on the gateway side, but I also don't see any `mongodb.default.dev01.internal.11c4a5d5-d6c7-fc12-7f78-362bc046db7f.consul` entry in the envoy config there

**Comment by blake** [comment]
Glad to hear you're making progress.

> but I also don't see any mongodb.default.dev01.internal.11c4a5d5-d6c7-fc12-7f78-362bc046db7f.consul entry in the envoy config there

Are you saying that this cluster is not present in the `/config_dump` for the terminating gateway? If it is in the config dump, is the external IP endpoint present in `/clusters`?

**Comment by remiphilippe** [comment]
long story short, no there isn't any config on the terminating gateway, more details

if we go: `[test pod] -> [terminating gateway] -> [minio]` 

on test pod, everything looks good config wise:
filter chain is there:
```
{
                  "filter_chain_match": {
                    "prefix_ranges": [
                      {
                        "address_prefix": "240.0.0.2",
                        "prefix_len": 32
                      }
                    ]
                  },
                  "filters": [
                    {
                      "name": "envoy.filters.network.tcp_proxy",
                      "typed_config": {
                        "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
                        "stat_prefix": "upstream.minio.default.default.dev01",
                        "cluster": "minio.default.dev01.internal.ea60ee3d-3b89-4733-a9ed-4d47ad8bb80e.consul"
                      }
                    }
                  ]
                }
```

cluster is populated:
```
{
          "version_info": "e229d39a01499f8c2546a73d2259b48a600b412cf1fceb3affb66e18716ed080",
          "cluster": {
            "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
            "name": "minio.default.dev01.internal.ea60ee3d-3b89-4733-a9ed-4d47ad8bb80e.consul",
            "type": "EDS",
            "eds_cluster_config": {
              "eds_config": {
                "ads": {},
                "resource_api_version": "V3"
              }
            },
            "connect_timeout": "5s",
            "circuit_breakers": {},
            "outlier_detection": {},
            "transport_socket": {
              "name": "tls",
              "typed_config": {
                "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
                "common_tls_context": {
                  "tls_params": {},
                  "tls_certificates": [
                    {
                      "certificate_chain": {
                        "inline_string": "-----BEGIN CERTIFICATE-----\nMIICHjCCAcWgAwIBAgIBDjAKBggqhkjOPQQDAjAwMS4wLAYDVQQDEyVwcmktajIx\nZWJoMi5jb25zdWwuY2EuZWE2MGVlM2QuY29uc3VsMB4XDTIyMDExOTE5MjAzN1oX\nDTIyMDEyMjE5MjAzN1owADBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABBaHta5w\nsM18clm6CKHoVc/jCl23uVrZT4lyNNZS2EEnIo34ZOEcce80ByjAIdlVZ7VpHQFz\nS4tjyTkBSUPIS+Kjgf8wgfwwDgYDVR0PAQH/BAQDAgO4MB0GA1UdJQQWMBQGCCsG\nAQUFBwMCBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMCkGA1UdDgQiBCDf2fc2Wo3t\nK/2napHYiMBjzYicoppnxyGpMtmEabRcyDArBgNVHSMEJDAigCAgIIaK6cR6Q14d\nOhYUVCiry/zthyAr+ruWwdqgjMHpbjBlBgNVHREBAf8EWzBZhldzcGlmZmU6Ly9l\nYTYwZWUzZC0zYjg5LTQ3MzMtYTllZC00ZDQ3YWQ4YmI4MGUuY29uc3VsL25zL2Rl\nZmF1bHQvZGMvZGV2MDEvc3ZjL2F3cy1pbmdlc3QwCgYIKoZIzj0EAwIDRwAwRAIg\nLMeWOn4qB6sWileABRei97tqNW6DqB6Ak5L+D2J1e2MCIFnpd+eIlTp8pZia2IED\nbQegsecjhIEpChtq7rdd8wm+\n-----END CERTIFICATE-----\n"
                      },
                      "private_key": {
                        "inline_string": "[redacted]"
                      }
                    }
                  ],
                  "validation_context": {
                    "trusted_ca": {
                      "inline_string": "-----BEGIN CERTIFICATE-----\nMIICDjCCAbOgAwIBAgIBCTAKBggqhkjOPQQDAjAwMS4wLAYDVQQDEyVwcmktajIx\nZWJoMi5jb25zdWwuY2EuZWE2MGVlM2QuY29uc3VsMB4XDTIyMDExOTE5MTkwMloX\nDTMyMDExNzE5MTkwMlowMDEuMCwGA1UEAxMlcHJpLWoyMWViaDIuY29uc3VsLmNh\nLmVhNjBlZTNkLmNvbnN1bDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABK0Fv1Tm\nTbpzQfuooatq3T88k39REWq8+OnGhr7Rjd7m2JtB7N+CuOh7xp2hddOh2wWX6NYL\n2vTpf9YhEuWPot2jgb0wgbowDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQFMAMB\nAf8wKQYDVR0OBCIEICAghorpxHpDXh06FhRUKKvL/O2HICv6u5bB2qCMweluMCsG\nA1UdIwQkMCKAICAghorpxHpDXh06FhRUKKvL/O2HICv6u5bB2qCMweluMD8GA1Ud\nEQQ4MDaGNHNwaWZmZTovL2VhNjBlZTNkLTNiODktNDczMy1hOWVkLTRkNDdhZDhi\nYjgwZS5jb25zdWwwCgYIKoZIzj0EAwIDSQAwRgIhAOmliyrJV24HUTgAbloQiJyf\nyueJZlUn//uSaTipQg/4AiEAx8bwd8xnP9cf8/WgXE1PzoL2eKZG0SNLL2zbvTHm\nvrA=\n-----END CERTIFICATE-----\n"
                    },
                    "match_subject_alt_names": [
                      {
                        "exact": "spiffe://ea60ee3d-3b89-4733-a9ed-4d47ad8bb80e.consul/ns/default/dc/dev01/svc/minio"
                      }
                    ]
                  }
                },
                "sni": "minio.default.dev01.internal.ea60ee3d-3b89-4733-a9ed-4d47ad8bb80e.consul"
              }
            },
            "common_lb_config": {
              "healthy_panic_threshold": {}
            },
            "alt_stat_name": "minio.default.dev01.internal.ea60ee3d-3b89-4733-a9ed-4d47ad8bb80e.consul"
          },
          "last_updated": "2022-01-19T19:21:45.619Z"
        }
```

dns is resolving, but connection is reset:
```
curl minio.virtual.consul:9000 -v
*   Trying 240.0.0.2:9000...
* Connected to minio.virtual.consul (240.0.0.2) port 9000 (#0)
> GET / HTTP/1.1
> Host: minio.virtual.consul:9000
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

Now on terminating gateway, nothing related to minio:
```
curl -X POST http://localhost:19000/config_dump | grep minio
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40101    0 40101    0     0  1465k      0 --:--:-- --:--:-- --:--:-- 2061k
```

clusters is basically empty:
```
{
  "cluster_statuses": [
    {
      "name": "local_agent",
      "host_statuses": [
        {
          "address": {
            "socket_address": {
              "address": "192.168.65.4",
              "port_value": 8502
            }
          },
          "stats": [
            {
              "name": "cx_connect_fail"
            },
            {
              "value": "1",
              "name": "cx_total"
            },
            {
              "name": "rq_error"
            },
            {
              "name": "rq_success"
            },
            {
              "name": "rq_timeout"
            },
            {
              "value": "1",
              "name": "rq_total"
            },
            {
              "type": "GAUGE",
              "value": "1",
              "name": "cx_active"
            },
            {
              "type": "GAUGE",
              "value": "1",
              "name": "rq_active"
            }
          ],
          "health_status": {
            "eds_health_status": "HEALTHY"
          },
          "weight": 1,
          "locality": {}
        }
      ],
      "circuit_breakers": {
        "thresholds": [
          {
            "max_connections": 1024,
            "max_pending_requests": 1024,
            "max_requests": 1024,
            "max_retries": 3
          },
          {
            "priority": "HIGH",
            "max_connections": 1024,
            "max_pending_requests": 1024,
            "max_requests": 1024,
            "max_retries": 3
          }
        ]
      },
      "observability_name": "local_agent"
    },
    {
      "name": "self_admin",
      "host_statuses": [
        {
          "address": {
            "socket_address": {
              "address": "127.0.0.1",
              "port_value": 19000
            }
          },
          "stats": [
            {
              "name": "cx_connect_fail"
            },
            {
              "value": "1",
              "name": "cx_total"
            },
            {
              "name": "rq_error"
            },
            {
              "value": "13",
              "name": "rq_success"
            },
            {
              "name": "rq_timeout"
            },
            {
              "value": "13",
              "name": "rq_total"
            },
            {
              "type": "GAUGE",
              "value": "1",
              "name": "cx_active"
            },
            {
              "type": "GAUGE",
              "name": "rq_active"
            }
          ],
          "health_status": {
            "eds_health_status": "HEALTHY"
          },
          "weight": 1,
          "locality": {}
        }
      ],
      "circuit_breakers": {
        "thresholds": [
          {
            "max_connections": 1024,
            "max_pending_requests": 1024,
            "max_requests": 1024,
            "max_retries": 3
          },
          {
            "priority": "HIGH",
            "max_connections": 1024,
            "max_pending_requests": 1024,
            "max_requests": 1024,
            "max_retries": 3
          }
        ]
      },
      "observability_name": "self_admin"
    }
  ]
}
```

**Comment by remiphilippe** [comment]
Note sure if it's related, but I just noticed some ports are set to 0 when sourced from k8s sync:
```
[{
    "ID": "0a10131c-9aeb-38d2-c535-f2f70e793f31",
    "Node": "docker-desktop",
    "Address": "10.1.3.171",
    "Datacenter": "dev01",
    "TaggedAddresses": {
        "lan": "10.1.3.171",
        "lan_ipv4": "10.1.3.171",
        "wan": "10.1.3.171",
        "wan_ipv4": "10.1.3.171"
    },
    "NodeMeta": {
        "consul-network-segment": "",
        "host-ip": "192.168.65.4",
        "pod-name": "consul-dljd8"
    },
    "ServiceKind": "terminating-gateway",
    "ServiceID": "consul-local-gateway-855f576867-dhst8",
    "ServiceName": "local-gateway",
    "ServiceTags": [],
    "ServiceAddress": "10.1.3.172",
    "ServiceTaggedAddresses": {
        "consul-virtual:mongodb": {
            "Address": "240.0.0.3",
            "Port": 0
        },
        "consul-virtual:redis-master": {
            "Address": "240.0.0.4",
            "Port": 0
        },
        "consul-virtual:janusgraph": {
            "Address": "240.0.0.1",
            "Port": 0
        },
        "consul-virtual:minio": {
            "Address": "240.0.0.2",
            "Port": 0
        },
        "lan_ipv4": {
            "Address": "10.1.3.172",
            "Port": 8443
        },
        "wan_ipv4": {
            "Address": "10.1.3.172",
            "Port": 8443
        }
    },
    "ServiceWeights": {
        "Passing": 1,
        "Warning": 1
    },
    "ServiceMeta": {},
    "ServicePort": 8443,
    "ServiceSocketPath": "",
    "ServiceEnableTagOverride": false,
    "ServiceProxy": {
        "Mode": "",
        "Config": {
            "envoy_dns_discovery_type": "LOGICAL_DNS",
            "envoy_gateway_bind_tagged_addresses": false,
            "envoy_prometheus_bind_addr": "10.1.3.172:20200",
            "protocol": "grpc"
        },
        "MeshGateway": {},
        "Expose": {}
    },
    "ServiceConnect": {},
    "CreateIndex": 39,
    "ModifyIndex": 511
}]
```

**Comment by remiphilippe** [comment]
hey @Blake any other ideas or directions I good dig into?

**Comment by blake** [comment]
Hi @remiphilippe,

I took another look at your config. Did you happen to modify the policy associated with the terminating gateway's token to grant it `service:write` access to the `mongodb` service? I'm not seeing that step in the reproduction steps you provided. This is needed so that the terminating gateway can act as the proxy for the linked external service.

The documentation for terminating gateway config entry calls this requirement out under the [`services`](https://www.consul.io/docs/connect/config-entries/terminating-gateway#services) parameter, but its easy to miss.

> * Services (array<LinkedService>: <optional>) - A list of services to link with the gateway.…If Consul ACLs are enabled, the Terminating Gateway's ACL token must grant service:write for all linked services.

If you have not completed this step, the easiest way to make this change is by following these steps.

1. [Login to the Consul UI](https://www.consul.io/docs/k8s/installation/install#viewing-the-consul-ui).
1. Navigate to the Policies page and click on the `local-gateway-terminating-gateway-token` policy.
1. Add the following lines to the existing policy rules.

    ```hcl
    service "mongodb" {
      policy = "write"
      intentions = "read"
    }
    ```

1. Save the policy.
1. Remove the `mongodb` service from the `services` field in terminating gateway custom resource.

    ```yaml
    ---
    apiVersion: consul.hashicorp.com/v1alpha1
    kind: TerminatingGateway
    metadata:
      name: local-gateway
    spec:
      services: []
    ```

1. Apply the change with `kubectl`.
1. Re-add the service to the list of services for this terminating gateway.

    ```yaml
    ---
    apiVersion: consul.hashicorp.com/v1alpha1
    kind: TerminatingGateway
    metadata:
      name: local-gateway
    spec:
      services:
        - name: mongodb
    ```

I created a test environment using the info you provided, and confirmed the terminating gateway was showing configuration for the `mongodb` service after performing above steps. Let me know if this also resolves the issue for you.
