### ISSUE TITLE
Allow more parameters in connect mesh visualization dashboard link

### ISSUE THREAD

**Issue by nahsi** [hashicorp/consul#12401]
#### Feature Description

Allow more parameters in `ui_config.dashboard_url_templates.service`.
Parameters like `{{Service.Meta.xxx}}`.

This was actually allowed and worked back in version 1.9.x

#### Use Case(s)

Using Consul `meta` to provide links in topology visualization. For example, when registering service with:
```hcl
meta {
        dashboard = "G7Z29GzMGz"
        alloc_id = NOMAD_ALLOC_ID
      }
```

and
```yml
  ui_config:
     dashboard_url_templates:
      service: !unsafe "https://grafana.service.consul/d/{{Service.Meta.dashboard}}"
```

resulting link in the UI should be `https://grafana.service.consul/d/G7Z29GzMGz`
