### ISSUE TITLE
If tproxy is enabled, explicit upstreams with serviceresolver create no envoy listeners

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#13400]
#### Overview of the Issue

If you have tproxy enabled and you're using explicit upstreams, then no listeners will be configured for explicit upstreams that use virtual services (i.e. serviceresolver services).

#### Reproduction Steps

```yaml
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "upstream:8802"
        consul.hashicorp.com/transparent-proxy: "true"
        consul.hashicorp.com/envoy-extra-args: '--log-level debug'
```

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: upstream
spec:
  redirect:
    service: other-svc
```

No Envoy listener will be created on 8802.

If you turn off tproxy, then the listener gets created.

There are no errors logged in Envoy or Consul clients.

#### Consul version

`1.12.0`

**Comment by hashi-derek** [comment]
Fixed in 1.12, 1.13, 1.14

**Comment by jkirschner-hashicorp** [comment]
@hashi-derek, @freddygv : Does this ensure tproxy works for **both** of the following use cases?
- Accessing failover targets
- Accessing "virtual services" (such as a named service-resolver with no actual service instances with that name, that redirects to something else)

**Comment by hashi-derek** [comment]
> @hashi-derek, @freddygv : Does this ensure tproxy works for **both** of the following use cases?
> 
> * Accessing failover targets
> * Accessing "virtual services" (such as a named service-resolver with no actual service instances with that name, that redirects to something else)

@jkirschner-hashicorp It seems to be working fine for me. I just ran a test in k8s with 1.14 on a tweaked example of the counting-dashboard demo.

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: myupstream
spec:
  redirect:
    service: counting
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: counting
spec:
  failover:
    "*":
      service: "counting2"
```

The flow of data was:

dashboard -> myupstream (virtual service redirect) -> counting (failover alias) -> counting

The "counting" pod was killed, and the stream swapped over to:

dashboard -> myupstream (virtual service redirect) -> counting (failover alias) -> counting2
