### ISSUE TITLE
Transparent proxy dialed directly not working on Consul 1.14.0 and Consul K8s 1.0 

### ISSUE THREAD

**Issue by FelipeEmerim** [hashicorp/consul#15470]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Overview of the Issue

We are testing the 1.0.0 release of consul-k8s in our lab environment and could not get the dialed directly feature of transparent proxy to work. We have traefik as our ingress controller and it cannot reach pods by their IPs. Downgrading to 0.49.0 fixes the issue.

### Reproduction Steps

1. Deploy consul using the values supplied on version 1.0.0
2. Create two connect injected applications with the sidecar proxy injected. (nginx should probably be the easiest to test)
3. Add ServiceDefaults to one of them with the property transparentProxy.dialedDirectly: true
4. Add ServiceIntentions if needed allowing one of the apps to receive connections from the other.
5. Check that the app with dialedDirectly enabled cannot be reached by one of its pods' IPs. We ran wget from the other app. 
6. Check that when using the k8s service IP or kubernetes DNS it is possible to connect to the service

### Logs

Sadly, the components do not log any errors, and we even see that the ServiceDefaults was synced successfuly.

### Expected behavior

We expected the ingress to be able to dial the service using the pods' ips.

### Environment details

- Kubernetes version: v1.23.x
- Cloud Provider Azure
- Networking CNI plugin in use: Calico 

### Additional Context

Helm values:

```yaml
global:
  enableConsulNamespaces: false
  name: consul
  datacenter: dc
  logLevel: "error"
  logJSON: true
  metrics:
    enabled: true
    enableAgentMetrics: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
    httpsOnly: false
    serverAdditionalDNSSANs:
      ## Add the K8s domain name to the consul server certificate
      - "consul-k8s-service-url"
  ## For production turn on ACLs and gossipEncryption:
  # acls:
  #   manageSystemACLs: true
  # gossipEncryption:
  #   secretName: "consul-gossip-encryption-key"
  #   secretKey: "key"

server:
  replicas: 3
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
  extraConfig: |
    {
      "log_level": "error",
      "ui_config": {
        "dashboard_url_templates": {
          "service": "grafana-url"
        }
      }
    }

ui:
  enabled: true
  service:
    type: "ClusterIP"
  #   annotations: |
  #     'service.beta.kubernetes.io/azure-load-balancer-internal': "true"
  metrics:
    baseURL: metrics-url

# This is a demo prometheus, for demo purposes only
prometheus:
  enabled: false

acls:
  manageSystemACLs: false

connectInject:
  # This method will inject the sidecar container into Pods:
  enabled: true
  transparentProxy:
    defaultEnabled: true
    defaultOverwriteProbes: true
  # But not by default, only do this for Pods that have the explicit annotation:
  #        consul.hashicorp.com/connect-inject: "true"
  default: false
  replicas: 2
  resources:
    requests:
      cpu: 125m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  sidecarProxy:
    resources:
      requests:
        cpu: 125m
        memory: 128Mi
      limits:
        cpu: 125m
        memory: 128Mi

syncCatalog:
  # This method will automatically synchronize Kubernetes services to Consul:
  # (No sidecar is injected by this method):
  enabled: true
  # But not by default, only for Services that have the explicit annotation:
  #        consul.hashicorp.com/service-sync: "true"
  default: false
  # Synchronize from Kubernetes to Consul:
  toConsul: true
  # But not from Consul to K8s:
  toK8S: false
  k8sAllowNamespaces: ["*"]
  addK8SNamespaceSuffix: true
  # Change to debug for debugging
  logLevel: "error"
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "100m"

```

We also tried a clean install of v1.0.0, but still see the issue.
We also tried to set this using proxyDefaults, but got the same results.

This is the serviceDefaults manifest we are using:

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  labels:
    app: apps-nginx
  name: apps-nginx
  namespace: apps
spec:
  transparentProxy:
    dialedDirectly: true

```
