### ISSUE TITLE
Terminating Gateway fails to display linked services

### ISSUE THREAD

**Issue by mmisztal1980** [hashicorp/consul#15597]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

![image](https://user-images.githubusercontent.com/1357057/204602071-31eb59cb-3b1d-40ec-b7d8-64df0248a824.png)

We are attempting to setup communication between meshed pods (transparent proxy enabled) and externally hosted cloud services (storage, REST services etc.) While following [the documentation](https://developer.hashicorp.com/consul/docs/k8s/connect/terminating-gateways) we are noticing that the terminating-gateway fails to pickup configuration changes and displays 0 linked services

#### Reproduction Steps

Steps to reproduce this issue, eg:

- Provision an AKS cluster
- Deploy Consul to `consul` namespace via HELM
- Use the following values file:

<details>
  <summary>values.yaml</summary>

```yaml
global:
  enabled: true
  name: consul
  datacenter: west-europe
  metrics:
    enabled: true
    enableAgentMetrics: true
    enableGatewayMetrics: true
  image: hashicorp/consul:1.13.2
  imageK8S: hashicorp/consul-k8s-control-plane:0.49.0
  imageEnvoy: envoyproxy/envoy:v1.23.1
  imageConsulDataplane: hashicorp/consul-dataplane:1.0.0-beta1
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "20200"

consul:
  server:
    enabled: true
    replicas: 3

  controller:
    enabled: true

  connectInject:
    enabled: true
    transparentProxy:
      defaultEnabled: true
    #only services from namespace with label will join mesh
    namespaceSelector: |
      matchLabels:
        consul.hashicorp.com/connect-inject : enabled
    metrics:
      defaultEnabled: true
      defaultPrometheusScrapePort: 20200
      defaultPrometheusScrapePath: "/metrics"
    k8sDenyNamespaces:
    - azure-devops

  terminatingGateways:
    enabled: true
    defaults:
      replicas: 2
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "100Mi"
          cpu: "100m"

  syncCatalog:
    enabled: true
    toConsul: true
    toK8S: false
    syncClusterIPServices: true
    k8sAllowNamespaces: ["dev"]
    k8sDenyNamespaces: ["kube-system", "kube-public"]

  ui:
    enabled: true
    metrics:
      enabled: true
      provider: prometheus
      baseURL: <redacted>
    service:
      enabled: true
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations: |
        cert-manager.io/cluster-issuer: <redacted>
        cert-manager.io/common-name: <redacted>
      hosts:
        - host: consul.westeurope.<redacted>
          paths:
            - /
      pathType: "Prefix"
      tls:
        - hosts:
            - consul.westeurope.<redacted>
          secretName: consul-westeurope-<redacted>
```

</details>

- Create the following `ServiceDefaults` in the `dev` namespace:

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: github
spec:
  protocol: tcp
  destination:
    addresses:
    - "github.com"
    port: 443
```

- Create the following `TerminatingGateway` in the `dev` namespace:

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: github-gateway
spec:
  services:
    - name: github
```

- Check UI, terminating-gateway displays 0 linked services
- Deploy a meshed ubuntu pod in the `dev` namespace with the following annotations:

```yaml
spec:
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
```

-  attempt to curl https://github.com:
```
root@service-a-55f66ffb5c-jk4zj:/# curl https://github.com
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
```

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease = 
        revision = 0e046bbb
        version = 1.13.2
        version_metadata = 
consul:
        acl = disabled
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 53
        max_procs = 4
        os = linux
        version = go1.18.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 2
        failed = 10
        health_score = 0
        intent_queue = 0
        left = 6
        member_time = 59027
        members = 24
        query_queue = 0
        query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease = 
        revision = 0e046bbb
        version = 1.13.2
        version_metadata = 
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = 10.126.216.99:8300
        server = true
raft:
        applied_index = 281532
        commit_index = 281532
        fsm_pending = 0
        last_contact = 0
        last_log_index = 281532
        last_log_term = 2
        last_snapshot_index = 278682
        last_snapshot_term = 2
        latest_configuration = [{Suffrage:Voter ID:e05cdba9-2644-3868-c77d-9061fbef87f0 Address:10.126.216.99:8300} {Suffrage:Voter ID:c6f13016-587a-eb16-e8a7-bed852271c24 Address:10.126.216.17:8300} {Suffrage:Voter ID:0261ab49-1c1c-6187-14f3-883b194fcc6b Address:10.126.216.51:8300}]
        latest_configuration_index = 0
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 238
        max_procs = 4
        os = linux
        version = go1.18.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 2
        failed = 10
        health_score = 0
        intent_queue = 0
        left = 6
        member_time = 58975
        members = 24
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 4
        members = 3
        query_queue = 0
        query_time = 1
```

</details>

### Operating system and Environment details

AKS 1.24.3 with Azure CNI enabled

### Log Fragments

```
2022-11-29T14:04:47.606Z [WARN] agent.server.catalog: no terminating-gateway or ingress-gateway associated with this gateway: gateway=terminating-gateway
```

**Comment by blake** [comment]
The default name for a terminating gateway instantiated by the Helm chart is `terminating-gateway`. (This can be controlled through the setting [`terminatingGateways.gateways.[0].name`](https://developer.hashicorp.com/consul/docs/k8s/helm#v-terminatinggateways-gateways-name).)

Your service defaults config should reference name `terminating-gateway` in the `metadata.name` field.

```yaml
# updated service defaults
apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: terminating-gateway
spec:
  services:
    - name: github
```

Or the TGW name in the Helm chart should be changed to `github-gateway`.

```yaml
# values.yaml
terminatingGateways:
  gateways:
    - name: github-gateway
```
