### ISSUE TITLE
doc: Federation Between Kubernetes Clusters with Vault as Secrets Backend 

### ISSUE THREAD

**Issue by natemollica-nm** [hashicorp/consul#16596]
#### Overview of the Issue

Consul on Kubernetes Integration with Vault as Secrets Backend documentation needs update to include bootstrap token, and override to include the `createReplicationToken: true` for proper ACL bootstrapping, and primary to secondary DC replication.

---

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Follow [doc](https://developer.hashicorp.com/consul/docs/k8s/deployment-configurations/vault/wan-federation) to create and deploy two Consul WAN Federated MeshGW clusters backed with Vault secrets engine.
1. When attempting to deploy primary Consul DC in step 4. of [Primary Datacenter (dc1)](https://developer.hashicorp.com/consul/docs/k8s/deployment-configurations/vault/wan-federation#primary-datacenter-dc1-1), Consul servers fail to bootstrap ACLs as indicated by 

#### server-acl-init pod

```shell-interactive
server-acl-init-job 2023-03-06T22:35:55.703Z [ERROR] consul-server-connection-manager: connection error: error="fetching supported dataplane features: rpc error: code = Unauthenticated desc = ACL not found"
```

#### consul-server-0 pod

```shell-interactive
consul 2023-03-06T22:35:05.181Z [ERROR] agent.anti_entropy: failed to sync remote state: error="ACL not found"  
```

#### connect-injector pod 

```shell-interactive
sidecar-injector 2023-03-06T22:36:25.908Z [ERROR] consul-server-connection-manager: connection error: error="rpc error: code = InvalidArgument desc = auth method \"consul-k8s-component-auth-method\" not found"
```

#### consul-mesh-gateway pod

```shell-interactive
mesh-gateway-init 2023-03-06T22:37:29.218Z [ERROR] consul-server-connection-manager: ACL auth method login failed: error="rpc error: code = InvalidArgument desc = auth method \"consul-k8s-component-auth-method\" not found"
```

### Consul Overrides (from doc)

<details>
  <summary>dc1-consul.yaml</summary>

```
global:
  datacenter: "dc1"
  name: consul
  secretsBackend:
    vault:
      enabled: true
      consulServerRole: consul-server
      consulClientRole: consul-client
      consulCARole: consul-ca
      manageSystemACLsRole: server-acl-init
      connectCA:
        address: http://vault-dc1.default:8200
        rootPKIPath: connect_root/
        intermediatePKIPath: dc1/connect_inter/
        authMethodPath: kubernetes-dc1
  tls:
    enabled: true
    enableAutoEncrypt: true
    caCert:
      secretName: pki/cert/ca
  federation:
    enabled: true
  acls:
    manageSystemACLs: true
    replicationToken:
      secretName: consul/data/secret/replication
      secretKey: token
  gossipEncryption:
    secretName: consul/data/secret/gossip
    secretKey: key
server:
  replicas: 1
  serverCert:
    secretName: "pki/issue/consul-cert-dc1"
connectInject:
  replicas: 1
  enabled: true
meshGateway:
  enabled: true
  replicas: 1

```

</details>

<details>
  <summary>dc2-consul.yaml</summary>

```
global:
  datacenter: "dc2"
  name: consul
  secretsBackend:
    vault:
      enabled: true
      consulServerRole: consul-server
      consulClientRole: consul-client
      consulCARole: consul-ca
      manageSystemACLsRole: server-acl-init
      connectCA:
        address: ${VAULT_ADDR}
        rootPKIPath: connect_root/
        intermediatePKIPath: dc2/connect_inter/
        authMethodPath: kubernetes-dc2
  tls:
    enabled: true
    enableAutoEncrypt: true
    caCert:
      secretName: "pki/cert/ca"
  federation:
    enabled: true
    primaryDatacenter: dc1
    k8sAuthMethodHost: ${KUBE_API_URL_DC2}
    primaryGateways:
    - ${MESH_GW_HOST}:443
  acls:
    manageSystemACLs: true
    replicationToken:
      secretName: consul/data/secret/replication
      secretKey: token
  gossipEncryption:
    secretName: consul/data/secret/gossip
    secretKey: key
server:
  replicas: 1
  serverCert:
    secretName: "pki/issue/consul-cert-dc2"
connectInject:
  replicas: 1
  enabled: true
controller:
  enabled: true
meshGateway:
  enabled: true
  replicas: 1

```

</details>

### Operating system and Environment details

* Kubernetes v1.24.0
* hashicorp/consul-enterprise:1.14.4-ent
* hashicorp/consul-k8s-control-plane:1.1.0
* hashicorp/vault-enterprise:1.12.3-ent
* hashicorp/vault-k8s:1.1.0
