### ISSUE TITLE
 Consul Service Mesh not working in Single Consul Datacenter Across Multiple Kubernetes Clusters

### ISSUE THREAD

**Issue by gouravchawate** [hashicorp/consul#16849]
#### Overview of the Issue

By referring to [consul documentation](https://developer.hashicorp.com/consul/docs/k8s/deployment-configurations/single-dc-multi-k8s), I am trying to Deploy Single Consul Datacenter Across Multiple Kubernetes Clusters. I have two k8 clusters, in one cluster I have installed consul server using helm and in other cluster I have installed consul connect using helm. Consul Connect on second cluster is joined to consul server on first cluster.

As given in documentation, I have deployed static-server service in first cluster where consul server is running and deployed static-client service in second cluster where the consul connect is running.
Now both the services static-server and static-client are registered with consul server and am able to view both the services in consul UI and in cli using consul catalog services.

But the issue is that static-client service in second cluster is unable to connect/communicate with static-server service in first cluster. If I deploy both services in same cluster then they are able to connect but when they are in different clusters they are unable to connect.

#### Reproduction Steps
1. Install consul server in first cluster using helm chart
2. Install consul connect components on second cluster using helm chart
3. Deploy static-server pod in first cluster
4. Deploy static-client pod in second cluster
5. From static-client, execute below command:
    curl localhost:1234

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
global:
  enabled: false
  datacenter: dc1
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: server-consul-bootstrap-acl-token
      secretKey: token
  tls:
    enabled: true
    caCert:
      secretName: server-consul-ca-cert
      secretKey: tls.crt
externalServers:
  enabled: true
  hosts: ["172.18.0.2"]
  httpsPort: 31306
  grpcPort: 30014
  tlsServerName: server.dc1.consul
  k8sAuthMethodHost: https://172.18.0.3:6443
connectInject:
  enabled: true
```
</details>

<details>
  <summary>Server info</summary>

```
global:
  datacenter: dc1
  tls:
    enabled: true
    enableAutoEncrypt: true
  acls:
    manageSystemACLs: true
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key
server:
  exposeService:
    enabled: true
    type: NodePort
    nodePort:
      ## all are random nodePorts and you can set your own
      http: 30010
      https: 30011
      serf: 30012
      rpc: 30013
      grpc: 30014
ui:
  service:
    type: NodePort
```

</details>

<details>
  <summary>static-server.yaml</summary>

```
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: static-server
spec:
  destination:
    name: static-server
  sources:
    - name: static-client
      action: allow
---
apiVersion: v1
kind: Service
metadata:
  name: static-server
spec:
  type: ClusterIP
  selector:
    app: static-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server
  template:
    metadata:
      name: static-server
      labels:
        app: static-server
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
        - name: static-server
          image: hashicorp/http-echo:latest
          args:
            - -text="hello world"
            - -listen=:8080
          ports:
            - containerPort: 8080
              name: http
      serviceAccountName: static-server

```
</details>

<details>
  <summary>static-client.yaml</summary>

```
apiVersion: v1
kind: Service
metadata:
  name: static-client
spec:
  selector:
    app: static-client
  ports:
    - port: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-client
  template:
    metadata:
      name: static-client
      labels:
        app: static-client
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "static-server:1234"
    spec:
      containers:
        - name: static-client
          image: curlimages/curl:latest
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      serviceAccountName: static-client
```
</details>

### Operating system and Environment details

Two K8 clusters

### Log Fragments
When trying to access static-server service, getting below error:
```
[root@devops consul]# kubectl exec -it static-client-5c6fcb95bb-xc4zx -c static-client -- curl localhost:1234
curl: (56) Recv failure: Connection reset by peer
command terminated with exit code 56
```
