### ISSUE TITLE
Consul streaming leaking rpc connections

### ISSUE THREAD

**Issue by weichuliu** [hashicorp/consul#17369]
#### Overview of the Issue

Consul client is leaking gRPC connections (1 per several minutes) when serving streaming requests.

On 1.10+, with streaming_backend enabled, Consul client agent will handle blocking queries with streaming -- it maintains a cache and establish a "subscription" on the change using gRPC to talk to Consul servers.

In our deployment, our Consul client agent are constantly getting lot of blocking queries. All subscriptions are supposed to use 1 single gRPC connection. However, we see `consul.grpc.client.connections` growing over time.

In the TRACE log, we found that the gRPC Router manager is constantly (every several minutes) refreshing gRPC connection, i.e. creating a new gRPC connection to replace the old one.

```
2023-05-10T06:30:48.552Z [TRACE] agent: [core][Channel #1] Resolver state updated: {
   ...
} ()
2023-05-10T06:30:48.552Z [TRACE] agent: [core][Channel #1 SubChannel #1442] Subchannel created
2023-05-10T06:30:48.552Z [TRACE] agent: [core][Channel #1] Channel Connectivity change to IDLE
2023-05-10T06:30:48.552Z [TRACE] agent: [core][Channel #1 SubChannel #1442] addrConn: tryUpdateAddrs curAddr: {
  ...
}
2023-05-10T06:30:48.552Z [TRACE] agent: [core][Channel #1 SubChannel #1440] Subchannel Connectivity change to SHUTDOWN
2023-05-10T06:30:48.552Z [TRACE] agent: [core][Channel #1 SubChannel #1440] Subchannel deleted
2023-05-10T06:30:48.552Z [TRACE] agent: [core][Channel #1 SubChannel #1442] Subchannel Connectivity change to CONNECTING
2023-05-10T06:30:48.552Z [TRACE] agent: [core][Channel #1 SubChannel #1442] Subchannel picks a new address "server1:8300" to connect
2023-05-10T06:30:48.552Z [TRACE] agent: [core][Channel #1] Channel Connectivity change to CONNECTING
2023-05-10T06:30:48.553Z [DEBUG] agent.router.manager: Rebalanced servers, new active server: ...
2023-05-10T06:30:48.554Z [TRACE] agent: [core][Channel #1 SubChannel #1442] Subchannel Connectivity change to READY
2023-05-10T06:30:48.554Z [TRACE] agent: [core][Channel #1] Channel Connectivity change to READY
```

During such event, usually the `consul.grpc.client.connections` will be `x`, then `x+1` and back to `x`. Which is the new connection replacing old one.

However, when there are active blocking queries, the old subscriptions will be holding the old gRPC connection, prevent it from closing. so `consul.grpc.client.connections` is `x` -> `x+1`, and keeps growing.

In our deployment, a single client agent can easily have more than 300 gRPC connections.

---

#### Reproduction Steps

1. Setup a Consul cluster with 3 servers and 1 client. Nothing special. I tested on `1.14.6` and `1.15.2` and both can reproduce the issue.
2. Config `telemery` for Consul client, and monitor `consul.grpc.client.connections` metrics.
3. Run `consul monitor -log-level trace | grep -i channel` on client side, to catch the gRPC rebalance event.
4. Create 10 fake service on client: `for i in $(seq 100); do consul services register -name test$i; done`.
5. Wait for the `Subchannel Connectivity change to READY` TRACE log, then start a new watch: `consul watch -type=service -service=test1 cat`.
6. Repeat step 5. Kick a new `consul watch` after a gRPC rebalance happened.
7. Check the telemetry and observe the growth of connections.

#### Expected behavior

Old gRPC connection should be released and closed, and the overall `grpc.client.connections` should always be low.

### Consul info for both Client and Server

As long as Consul server/client support streaming.

### Operating system and Environment details

This bug is OS agnostic.

**Comment by weichuliu** [comment]
When we stop sending blocking queries to a Consul client, it takes 20 minutes to gradually evict sub-material view caches, and we can see `grpc.client.connections` gradually drop from 400 to less than 10 during the period.

**Comment by huikang** [comment]
@weichuliu , thanks for your time investigating this issue and the deep analysis. We will look into this issue ASAP.

**Comment by weichuliu** [comment]
Thanks @huikang I'm looking forward to the fix.

This one is pretty annoying for us, and I believe it's annoying for anyone that uses streaming feature.

**Comment by jmurret** [comment]
Hi @weichuliu, I cannot recreate this on the latest consul nor consul 1.15.2.  I have created watches after each rebalancing and also waited for the rebalancing to get back to the original server.  

I have use the following configuration on kubernetes:

```
global:
  enabled: true
  name: consul
  datacenter: dc1
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: "1m"
  image: hashicorp/consul:1.15.2
  imageK8S: hashicorp/consul-k8s-control-plane:1.1
server:
  replicas: 3
client:
  enabled: true
  extraConfig: |
    {"use_streaming_backend": true}
ui:
  enabled: true
  metrics:
    enabled: true
    provider: "prometheus"
    baseURL: http://prometheus-server.default.svc.cluster.local
connectInject:
  enabled: true
  default: true
controller:
  enabled: true
```

Could you provide the simplest configuration that you used for the recreation steps?
