### ISSUE TITLE
prometheus metrics via the ui endpoint are incorrect `v1.15.3`

### ISSUE THREAD

**Issue by walter-staked** [hashicorp/consul#17807]
Scraping `consul_autopilot_healthy` with prometheus returns `0` even thought  `/v1/operator/autopilot/health` returns `Healthy: true,`
#### Overview of the Issue

`Given:` consul exposes endpoint http://<SEVER>/v1/agent/metrics?format=prometheus
`When:` Prometheus scrapes the end point
`Then:` endpoints should report same results as curling the local host endpoints 
`Expected:`    consul_autopilot_healthy 1 for a healthy cluster 
`Actual:`  
```
# HELP consul_autopilot_failure_tolerance Tracks the number of voting servers that the cluster can lose while continuing to function.
# TYPE consul_autopilot_failure_tolerance gauge
# this should match raft size in this case its' a  cluster of 5 servers
#ACTUAL 
consul_autopilot_failure_tolerance 0


# HELP consul_version Represents the Consul version.
# TYPE consul_version gauge
# This should be `v1.15.3`
# ACTUAL 
consul_version 0

# HELP consul_autopilot_healthy Tracks the overall health of the local server cluster. 1 if all servers are healthy, 0 if one or more are unhealthy.
# TYPE consul_autopilot_healthy gauge
# this should be one 
#ACTUAL
consul_autopilot_healthy 0
```
---

#### Reproduction Steps
Steps to reproduce this issue, eg:
`Values.yaml`
```
global:
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: 1h
  peering:
    enabled: false
  datacenter: hashicorp-test-cluster
  tls:
    enabled: false
    enableAutoEncrypt: false
    httpsOnly: false
server:
  replicas: 5
ui:
  enabled: true
  metrics:
    enabled: true
    provider: "prometheus"
  ingress:
    enabled: true
    annotations: |
      'nginx.ingress.kubernetes.io/ssl-redirect': "false"
metrics:
  enabled: true
  provider: "prometheus"
```
` helm install consul hashicorp/consul -f values.yaml`

1. kubectl exec into the pod 
2. Run  curl localhost:8500/v1/operator/autopilot/health | jq . 
3. healthy cluster returns `Healthy:` true,
4. visit consul's ingress at <your consuls url>/v1/agent/metrics?format=prometheus and view consul_autopilot_failure_tolerance
```
# HELP consul_autopilot_failure_tolerance Tracks the number of voting servers that the cluster can lose while continuing to function.
# TYPE consul_autopilot_failure_tolerance gauge
# this should match raft size in this case its' a  cluster of 5 servers
#ACTUAL 
consul_autopilot_failure_tolerance 0


# HELP consul_version Represents the Consul version.
# TYPE consul_version gauge
# This should be `v1.15.3`
# ACTUAL 
consul_version 0

# HELP consul_autopilot_healthy Tracks the overall health of the local server cluster. 1 if all servers are healthy, 0 if one or more are unhealthy.
# TYPE consul_autopilot_healthy gauge
# this should be one 
#ACTUAL
consul_autopilot_healthy 0
```

### Consul info for both Client and Server

Output from client 'consul info' command here
```

Only running servers in this config 
```
Client agent HCL config
```

</details>

<details>
  <summary>Server info</summary>

```
Output from server 'consul info' command here
```

```
Server agent HCL config
```


<details>
  <summary>Client info</summary>
```
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 7ce982ce
	version = 1.15.3
	version_metadata =
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = redacted:8300
	server = true
raft:
	applied_index = 253349759
	commit_index = 253349759
	fsm_pending = 0
	last_contact = 16.291258ms
	last_log_index = 253349759
	last_log_term = 1813
	last_snapshot_index = 253335329
	last_snapshot_term = 1813
	latest_configuration = [{redacted}]
	latest_configuration_index = 0
	num_peers = 4
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 1813
runtime:
	arch = amd64
	cpu_count = 16
	goroutines = 153
	max_procs = 16
	os = linux
	version = go1.20.4
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 618
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 5973
	members = 5
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 3161
	members = 5
	query_queue = 0
	query_time = 1
	```

</details>
