### ISSUE TITLE
consul server fails with "failed to parse /consul/extra-config/locality.json: 1 error occurred"

### ISSUE THREAD

**Issue by Rudraksh95** [hashicorp/consul#18079]
**Steps to reproduce:**
Apply following yaml file.

helm upgrade --install consul hashicorp/consul -n <NS> -f consul.yaml

```
global:
  enabled: true
  logLevel: "info"
  logJSON: false
  name: consul
  domain: consul
  image: consul:1.15.4
  imagePullSecrets: []
  imageK8S: docker.mirror.hashicorp.services/hashicorppreview/consul-k8s-control-plane:1.2.0-dev
  datacenter: dc1
  enablePodSecurityPolicies: false
  gossipEncryption:
    autoGenerate: true
    secretName: ""
    secretKey: ""

server:
  enabled: "-"
  replicas: 3
  storage: 10Gi
  storageClass: "px-replicated"
  #storageClass: null
  resources:
    requests:
      memory: "128Mi"
      cpu: "200m"
    limits:
      memory: "256Mi"
      cpu: "250m"
dns:
  enabled: "-"
  enableRedirection: "-"
  type: ClusterIP
  clusterIP: null
  annotations: null

ui:
  enabled: "-"
  service:
    enabled: true
    type: null
    port:
      http: 80
      https: 443
    nodePort:
      http: null
      https: null
    annotations: null
    additionalSpec: null
  ingress:
    enabled: true
    ingressClassName: ""
    pathType: Prefix
    hosts:
      - host: ing
        paths:
          - /
  metrics:
    enabled: "-"
syncCatalog:
  k8sAllowNamespaces: ["<ns>"]

connectInject:
  enabled: true
  replicas: 1
  image: null
  default: false

  apiGateway:
    manageExternalCRDs: true
    managedGatewayClass:
      nodeSelector: null
      tolerations: null
      serviceType: ClusterIP
      copyAnnotations:
        service: null
      deployment: 
        defaultInstances: 1
        maxInstances: 1
        minInstances: 1
    serviceAccount:
      annotations: null
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "100m"
  resources:
    requests:
      memory: "200Mi"
      cpu: "50m"
    limits:
      memory: "200Mi"
      cpu: "50m"
  sidecarProxy:
    concurrency: 2
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "100m"
  initContainer:
    resources:
      requests:
        memory: "150Mi"
        cpu: "150m"
      limits:
        memory: "200Mi"
        cpu: "200m"

tests:
  enabled: true

```
consul-server pod crashes with the following error
```
consul ==> failed to parse /consul/extra-config/locality.json: 1 error occurred:
consul     * invalid config key locality
```
