### ISSUE TITLE
Failed to query the DNS server

### ISSUE THREAD

**Issue by jimmypk** [hashicorp/consul#1821]
I use lua-nginx to query Consul DNS (SRV Record) many times. And sometime it raises the below error:

Failed to query the DNS server: failed to receive reply from UDP server 192.168.x.x:8600: timeout

How to solve that.
Thanks.

**Comment by slackpad** [comment]
Hi @jimmypk it's hard to tell what's going on - are there any interesting logs from Consul that correlate to these timeouts? It could also be related to heavy packet loss if you have a heavily loaded instance. Any additional details you can provide would be helpful.

**Comment by Van-Tien** [comment]
126#0: *22 [lua] access.lua:8: log(): CONSUL DNS: Failed to query the DNS server: failed to receive reply from UDP server 192.168.1.3:8600: timeout
, client: 192.168.10.50, server: _, request: "POST /sessions.json HTTP/1.1", host: "abc.testing.com"
2016/06/16 15:30:09 [error] 126#0: *22 failed to run body_filter_by_lua*: /usr/local/share/lua/5.1/kong/core/handler.lua:87: attempt to perform arithmetic on field 'KONG_HEADER_FILTER_STARTED_AT' (a nil value)
stack traceback:
        /usr/local/share/lua/5.1/kong/core/handler.lua:87: in function 'after'
        /usr/local/share/lua/5.1/kong.lua:209: in function 'body_filter'
        body_filter_by_lua:2: in function <body_filter_by_lua:1>, client: 192.168.1.2, server: _, request: "POST /sessions.json HTTP/1.1", host: "abc.testing.com"

**Comment by slackpad** [comment]
Please re-open if you are still experiencing any issues.

**Comment by Modestying** [comment]
Consul port `8600` should set `udp` , port default `tcp`
eg:
```
  consul_server:
    image: consul:latest
    container_name: consul_server
    ports:
      - 8500:8500
      - 8600:8600/udp
    command: agent -server=true -client=0.0.0.0 --bootstrap-expect=1 --node=leader -ui
```
