### ISSUE TITLE
I set the environment variable CONSUL_ API_ PREFIX, but it doesn't seem to be working

### ISSUE THREAD

**Issue by feigaogit** [hashicorp/consul#18219]
consul 1.16.0
server centos7
docker-compose.yml:
```
version: '3'

services:
  consul:
    image: consul
    container_name: consul 
    environment:
      CONSUL_API_PREFIX: consul/
    volumes:
      - ./consul/config:/consul/config
      - ./consul/data:/consul/data
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"

  nginx:
    image: nginx
    container_name: nginx   
    volumes:      
      - ./nginx/config/conf.d/:/etc/nginx/conf.d/
      - ./nginx/log:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - 80:80
```
![image](https://github.com/hashicorp/consul/assets/18181270/903c2d75-a07c-42da-ba14-45fe506fa523)

The api url has not changed
![image](https://github.com/hashicorp/consul/assets/18181270/aa2217f9-b3e7-4538-994b-ff7bef1371d6)

What should I do？
