### ISSUE TITLE
Pod tags are not synced into Consul

### ISSUE THREAD

**Issue by Vetrenik** [hashicorp/consul#18392]
#### Overview of the Issue

I'm not sure, if i'm creating issue in the correct GIT repo.

I'm using `Service Sync` to sync my k8s services into Consul. When i'm using anntotations to add service tag, as in here:

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: readiness
  labels:
    app: readiness
  annotations:
    'consul.hashicorp.com/service-port': 'test1'
    'consul.hashicorp.com/service-tags': 'test'
spec:
  clusterIP: None
  ports:
  - port: 80 
    protocol: TCP
    targetPort: port1
    name: test1
  - port: 81
    protocol: TCP
    targetPort: port2
    name: test2

  selector:
    app: readiness
```

with `Pod`:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: readiness
  name: readiness-exec
spec:
  containers:
  - name: readiness
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 6000
    ports:
      - name: port1
        containerPort: 80
      - name: port2
        containerPort: 81

    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 1
      successThreshold: 1

```
 
All works fine and i could see tag `test` in Consul for service `readiness-default` and `Consul DNS` retruns correct entries for query `readiness-default.service.consul`
 
But when i'm adding `Pod` with this config:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: readiness
  name: readiness-exec1
  annotations:
    'consul.hashicorp.com/service-tags': 'test1'
spec:
  containers:
  - name: readiness
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 6000
    ports:
      - name: port1
        containerPort: 80
      - name: port2
        containerPort: 81

    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 1
      successThreshold: 1
```

`Consul DNS` still returnt correct number of entries for query `readiness-default.service.consul`, but no tag `test1` is produced for service instance and consul DNS return no entries for query `test1.readiness-default.service.consul`.

I'm using purely `Service sync` without `Service Mesh` enabled.

### Consul info for both Client and Server
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 53f65dc3
        version = 1.15.0
        version_metadata =
consul:
        acl = disabled
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 55
        max_procs = 2
        os = linux
        version = go1.20.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 9
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 14385
        members = 6
        query_queue = 0
        query_time = 1
```

```
Client agent HCL config
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 1
        checks = 2
        services = 2
build:
        prerelease =
        revision = 53f65dc3
        version = 1.15.0
        version_metadata =
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 10.74.102.22:8300
        server = true
raft:
        applied_index = 13549291
        commit_index = 13549291
        fsm_pending = 0
        last_contact = 319.278µs
        last_log_index = 13549291
        last_log_term = 18
        last_snapshot_index = 13547324
        last_snapshot_term = 18
        latest_configuration = [{Suffrage:Voter ID:078024ca-d4b6-1df7-8933-c3341dd6cf00 Address:10.74.102.23:8300} {Suffrage:Voter ID:8e886fcb-a2d8-8317-5186-09da9a842af0 Address:10.74.102.21:8300} {Suffrage:Voter ID:8edfafe2-5dfd-69fa-f73a-4151433687c9 Address:10.74.102.22:8300}]
        latest_configuration_index = 0
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 18
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 145
        max_procs = 2
        os = linux
        version = go1.20.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 9
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 14385
        members = 6
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 12
        members = 3
        query_queue = 0
        query_time = 1
```
