### ISSUE TITLE
The `consul` user does not have write access to /consul/data in the offical docker image. 

### ISSUE THREAD

**Issue by fxdgear** [hashicorp/consul#2025]
**The GH repo https://github.com/hashicorp/docker-consul does not support issues, so filing here.** 

### `consul version` for both Client and Server
Client: `consul:latest` https://hub.docker.com/r/library/consul/
Server: `consul:latest` https://hub.docker.com/r/library/consul/

### Operating system and Environment details

Offical Docker Image. https://github.com/hashicorp/docker-consul

### Description of the Issue (and unexpected/desired result)

When running docker-compose with the offical docker image I get the following error 
```
Error starting agent: Failed to start Consul server: Failed to start Raft: mkdir /consul/data/raft: permission denied
```
### Reproduction steps

docker-compose.yml
```yaml
consul:
  image: consul:latest
  command: agent -server -config-file /consul/config/consul.json -ui-dir /opt/consul/ui
  volumes:
    - "./services/vault/consul/assets/conf.d:/consul/config:ro"
    - "./services/vault/consul/data:/consul/data:rw"
```

Then run `docker-compose up`

But if I change the entrypoint
```yaml
consul:
  image: consul:latest
  entrypoint: /bin/consul   # < -- override the entry point here
  command: agent -server -config-file /consul/config/consul.json -ui-dir /opt/consul/ui
  volumes:
    - "./services/vault/consul/assets/conf.d:/consul/config:ro"
    - "./services/vault/consul/data:/consul/data:rw"
```

it works fine.
