### ISSUE TITLE
Consul ServiceRouter Configuration not applying

### ISSUE THREAD

**Issue by t3rmo** [hashicorp/consul#21561]
Hello, im new to Consul. Since a few days i cant get my ServiceRouter to work. 

I tryed reinstalling docker, uninstalling and installing consul over and over again but i cant get it to work. I dont use Enterprise.

How i setup Consul:

- helm repo add hashicorp https://helm.releases.hashicorp.com
- helm install consul hashicorp/consul --create-namespace --namespace consul --values values.yaml
- kubectl config set-context --current --namespace=default
- kubectl apply -f postgres.yaml
- kubectl apply -f backend.yaml
- kubectl apply -f proxy-defaults.yaml

After this i check my ServiceRouters and ServiceDestinations which show me that they are synced and running.
Still Timeouts and Retrys dont work. Intentions also dont seem to work, doesnt matter if i set them through UI or yaml files. Im not sure if thats due to a bug or something else.

The way i test is with Postman or hey. I port-forward my backend with kubectl port-forward service/backend 8080:8080 and send my requests then. Is that the correct procedure or am i missing something?

My values file:
```
global:
  name: consul-hofladen
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: "59m"
prometheus:
  enabled: true

ui:
  metrics:
    enabled: true
    provider: "prometheus"
    baseURL: http://prometheus-server
connectInject:
  enabled: true
  default: true
  metrics:
    defaultEnabled: true
    defaultEnableMerging: false
```

My backend.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      containers:
      - name: backend
        image: t3rmo/hofladen_backend:latest
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres.default.svc.cluster.local/hofladen"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
  annotations:
    consul.hashicorp.com/connect-service-upstreams: "api:8080"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: backend
  namespace: default
spec:
  protocol: http
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: backend
  namespace: default
spec:
  routes:
    - match:
        http:
          pathExact: /reservations/timeout
      destination:
        service: backend
        requestTimeout: 1s
        idleTimeout: 1s
```
