### ISSUE TITLE
Ability to set a tag on Consul's own service registration

### ISSUE THREAD

**Issue by far-blue** [hashicorp/consul#2299]
It would be useful if consul was able to add tags to its own service registration. This could be to allow referring to particular instances by DNS or it could be for external uses such as Fabio proxy routing.

**Comment by slackpad** [comment]
Hi @far-blue - what uses were you thinking of? We probably should just have Consul tag itself automatically for most things (leader, follower seems like a good one for servers), any other use cases you had in mind?

**Comment by far-blue** [comment]
leader / follower is a good example for an automated tag but tagging is also helpful just as labels for managing resources. Some third party apps such as Fabio and anything built using consul-template to react to service data also tend to use tags to identify or exclude services.

**Comment by slackpad** [comment]
Are you looking to add tags related to Consul's service itself, though, or are you more looking for tags that represent the node as a whole?

**Comment by far-blue** [comment]
That's a good question. I guess I was thinking in terms of Consul's Rest API as a service - much like Nomad and Vault present their API interface(s) as services and that is still my interest.

However, I guess it is also fair to say that nodes themselves could have tags rather than the consul service per-se. I guess this would be closer to Nomad's 'meta' info for agents. Grouping of nodes based on a tag would allow dns queries for nodes similar to services.

**Comment by bfgoodrich** [comment]
As far as tags for nodes - https://github.com/hashicorp/consul/issues/154

**Comment by bacoboy** [comment]
A good use case for this is when using [traefik](http://traefik.io)'s `consul_catalog`.

Consul's self registration gets picked up as a real service on port 8300.  The way you tell traefik to ignore this is by setting a tag `traefik.enable=false` on the service (like traefik does to its own services):
```
% curl -s http://127.0.0.1:8500/v1/catalog/services | jq
{
  "consul": [],
  "traefik-dashboard": [
    "traefik.enable=false"
  ],
  "traefik-http": [
    "traefik.enable=false"
  ]
}
```

I stumbled across this issue looking for how to set a tag on consul's self-registration 😉

**Comment by sev3ryn** [comment]
I'm using tags to point Prometheus what services to scrape for metrics and what metric_path to use - this would be useful to be able to scrape from Consul's `/v1/agent/metrics?format=prometheus` endpoint

**Comment by Artanicus** [comment]
Any updates to this one? While I can manage any service in Consul with tags to configure it for Traefik, ironacally I cannot manage the Consul UI itself since I cannot add tags to it that would then be consumed by the Traefik consul_catalog. I can configure it as a static Traefik routing but then lose health check based load balancing.

**Comment by blmhemu** [comment]
Hello @Artanicus ! May I ask, if you can share your static config. I am looking for something similar and came across this...

**Comment by itorres** [comment]
@blmhemu something like this will expose the local consul agent (and in our case also nomad):
```
http:                                    
  routers:                               
    consul:                              
      rule: "Host(`consul.example.net`)"
      service: "consul"                  
    nomad:                               
      rule: "Host(`nomad.example.net`)" 
      service: "nomad"                   
  services:                              
    consul:                              
      loadBalancer:                      
        servers:                         
          - url: "http://localhost:8500" 
    nomad:                               
      loadBalancer:                      
        servers:                         
          - url: "http://localhost:4646" 
```
