### ISSUE TITLE
docker Consul Failed because it cannot parse advertise address

### ISSUE THREAD

**Issue by notuscloud** [hashicorp/consul#2820]
### `consul version` for both Client and Server
Client: `0.7.5`
Server: `0.7.5`

### Operating system and Environment details
Docker 17.03.0-ce, under CentOS 7.3.1611

### Description of the Issue (and unexpected/desired result)
I can't start consul in client mode.

### Reproduction steps

Use this docker-compose file:
```
version: "2"
services:
  consul-client:
    image: consul:0.7.5
    network_mode: host
    container_name: consul
    restart: always
    environment:
      - CONSUL_BIND_INTERFACE=eno33557248
    volumes:
      - /opt/docker/consul/agent/data:/consul/data
    command:
      - consul
      - agent
      - -data-dir=/consul/data
      - -bind=eno33557248
      - -client=eno33557248
      - -retry-join=some-working-consul-server
      - -log-level=TRACE
```
Then `docker-compose up`.

### Log Fragments or Link to [gist](https://gist.github.com/)

```
Attaching to consul
consul | ==> Found address '172.20.4.2' for interface 'eno33557248', setting bind option...
consul | ==> Starting Consul agent...
consul | ==> Error starting agent: Failed to start Consul client: Failed to start lan serf: Failed to create memberlist: Failed to parse advertise address!
```

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment]
Hi @notuscloud that error is coming from these two lines, which should be deleted:

```
      - -bind=eno33557248
      - -client=eno33557248
```

Consul doesn't know how to parse those, but setting `CONSUL_BIND_INTERFACE=eno33557248` should be sufficient (there's also `CONSUL_CLIENT_INTERFACE=eno33557248` you can set as well for the client socket). Hope that helps!

**Comment by notuscloud** [comment]
Hi @slackpad 

I tried with `CONSUL_CLIENT_INTERFACE=eno33557248` and I followed your advice, deleting the two lines `-client` and `-bind`.

```
consul | ==> Found address '172.20.4.2' for interface 'eno33557248', setting bind option...
consul | ==> Found address '172.20.4.2' for interface 'eno33557248', setting client option...
consul | ==> Starting Consul agent...
consul | ==> Error starting agent: Failed to get advertise address: Multiple private IPs found. Please configure one.
consul exited with code 1
```

I may be missing something...

Regards,
Thomas

**Comment by slackpad** [comment]
I think you want to set both `CONSUL_CLIENT_INTERFACE=eno33557248` and `CONSUL_CLIENT_INTERFACE=eno33557248` in your config. The client setting determines where Consul binds its HTTP and DNS endpoints for apps to talk to, and the bind interface is used for internal cluster communications (and will also set the advertise address for you).

**Comment by notuscloud** [comment]
Yes, I did that. If you look closely at those two lines:
```
consul | ==> Found address '172.20.4.2' for interface 'eno33557248', setting bind option...
consul | ==> Found address '172.20.4.2' for interface 'eno33557248', setting client option...
```

Both `CONSUL_CLIENT_INTERFACE=eno33557248` and `CONSUL_CLIENT_INTERFACE=eno33557248` are set.

Regards

**Comment by slackpad** [comment]
Hmm - need to take a deeper look.

**Comment by notuscloud** [comment]
Ok, 

I found the solution. If you look closely at the `docker-entrypoint.sh` script, available here https://github.com/hashicorp/docker-consul/blob/master/0.X/docker-entrypoint.sh, You'll see this part of the script:
```
if [ "$1" = 'agent' ]; then
    shift
    set -- consul agent \
        -data-dir="$CONSUL_DATA_DIR" \
        -config-dir="$CONSUL_CONFIG_DIR" \
        $CONSUL_BIND \
        $CONSUL_CLIENT \
        "$@"
```
I'm far from being an expert but it seems `CONSUL_CLIENT_INTERFACE=eno33557248` and `CONSUL_BIND_INTERFACE=eno33557248` are ignored if you override the default `CMD`+`ENTRYPOINT` specified in the Dockerfile.
But the way I used the docker-compose's directive `command`, I overridden the default `CMD` and thus I can't pass my parameters correctly. 

If you want to use docker-compose, as it is now, the `CONSUL_CLIENT_INTERFACE=eno33557248` cannot work either. As docker-compose cannot allow you to passe the `agent` argument, the docker-entrypoint.sh `$CONSUL_CLIENT` parameter is ignored because of this `CMD ["agent", "-dev", "-client", "0.0.0.0"]`

The workaround I found is to use this docker-compose file:
```
version: "2"
services:
  consul-client:
    image: consul:0.7.5
    network_mode: host
    container_name: consul
    restart: always
    environment:
      - CONSUL_BIND_INTERFACE=eno33557248
      - CONSUL_CLIENT_INTERFACE=eno33557248
    volumes:
      - /opt/docker/consul/agent/data:/consul/data
      - ./config:/consul/config
    command:
       - /usr/local/bin/docker-entrypoint.sh
       - agent
```

Thanks for your time.
Regards,
Thomas
