### ISSUE TITLE
Discover multiple instances of a docker service registered via consul agent on host machine

### ISSUE THREAD

**Issue by txfan** [hashicorp/consul#3481]
It seems that we need to build consul into docker image together with application service, so that multiple instance of a service running on the same physical machine can be discovered by consul, just like this project did: 
- https://github.com/rodrigozc/jdk8-filebeat-consul

What is the best practice of deploying consul with dockerized services on physical machines? Is it possible to deploy consul agent per physical server node? Following is what we encountered:

### Operating system and Environment details

- CentOS Linux release 7.4.1708 (Core)
- Docker version 17.06.2-ce, build cec0b72
- Spring Cloud Consul 1.2.1.RELEASE
- Consul 0.9.2

### Description of the Issue (and unexpected/desired result)

We have a cluster of physical machines initialized with docker swarm and consul. Our services are built with spring cloud config and docker. When deploying a service with docker swarm and scale it to multiple instances. We found the instances on the same node can only have one discovered by consul.

    # consul members
    Node      Address           Status  Type    Build  Protocol  DC
    node-1  10.201.15.2:8301  alive   server  0.9.2  2         dc1
    node-2  10.201.16.2:8301  alive   server  0.9.2  2         dc1
    node-3  10.201.17.2:8301  alive   server  0.9.2  2         dc1
    node-4  10.201.18.2:8301  alive   client  0.9.2  2         dc1
    node-5  10.201.19.2:8301  alive   client  0.9.2  2         dc1

Note that the docker image is not packaged with consul agent. We mounted a config file, bootstrap.properties, into the docker container, so that spring cloud application can get the IP of the host machine and register on the corresponding consul agent.

### Reproduction steps

docker-compose.yml:

```yml
version: '3.2'
services:
  api:
    image: registry.example.com/example/example-api
    networks:
      - infra
   environment:
      - CI_ENVIRONMENT_SLUG=${CI_ENVIRONMENT_SLUG:-local}
      - CI_ENVIRONMENT_TIMEZONE=${CI_ENVIRONMENT_TIMEZONE:-Asia/Shanghai}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-debug}
      - SPRING_CLOUD_CONFIG_LABEL=${SPRING_CLOUD_CONFIG_LABEL:-master}
    volumes:
      - ./bootstrap.properties:/app/bootstrap.properties
  foo:
    image: registry.example.com/example/example-foo
    networks:
      - infra
    environment:
       - CI_ENVIRONMENT_SLUG=${CI_ENVIRONMENT_SLUG:-local}
       - CI_ENVIRONMENT_TIMEZONE=${CI_ENVIRONMENT_TIMEZONE:-Asia/Shanghai}
       - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-debug}
       - SPRING_CLOUD_CONFIG_LABEL=${SPRING_CLOUD_CONFIG_LABEL:-master}
     volumes:
       - ./bootstrap.properties:/app/bootstrap.properties
  bar:
    image: registry.example.com/example/example-bar
    networks:
      - infra
   environment:
      - CI_ENVIRONMENT_SLUG=${CI_ENVIRONMENT_SLUG:-local}
      - CI_ENVIRONMENT_TIMEZONE=${CI_ENVIRONMENT_TIMEZONE:-Asia/Shanghai}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-debug}
      - SPRING_CLOUD_CONFIG_LABEL=${SPRING_CLOUD_CONFIG_LABEL:-master}
    volumes:
      - ./bootstrap.properties:/app/bootstrap.properties
networks:
  infra:
    external: true
```
bootstrap.properties on `node-1`
```properties
spring.cloud.consul.host=10.201.15.2
```
bootstrap.properties on `node-2`
```properties
spring.cloud.consul.host=10.201.16.2
```
...

 To deploy/scale the services:

    docker stack deploy -c docker-compose.yml example
    docker stack scale example_api=3

To scale on a specific node (e.g. `node-2` as below), just add some labels and constraints.

    # docker service ps example_api
    ID                  NAME                IMAGE                                NODE                DESIRED STATE           CURRENT STATE         ERROR               PORTS
    vqkqva0dka0h        example_api.1        registry.example.com/example/example-api:latest   node-2            Running             Running 2 hours ago
    0sv2jg33i3s1        example_api.2        registry.example.com/example/example-api:latest   node-2            Running             Running 2 hours ago
    ltvq1zxgawln        example_api.3        registry.example.com/example/example-api:latest   node-2            Running             Running 2 hours ago

curl http://10.201.16.130:8086/consul

```json
{
  "catalogServices": {
    "example-api": [
      {
        "node": "node-2",
        "address": "10.201.16.2",
        "serviceId": "example-api-debug-8086",
        "serviceName": "example-api",
        "serviceTags": [],
        "serviceAddress": "10.201.16.130",
        "servicePort": 8086
      }
    ]
  },
  "catalogNodes": [
    {
      "node": "node-1",
      "address": "10.201.15.2"
    },
    {
      "node": "node-2",
      "address": "10.201.16.2"
    },
    {
      "node": "node-3",
      "address": "10.201.17.2"
    },
    {
      "node": "node-4",
      "address": "10.201.18.2"
    },
    {
      "node": "node-5",
      "address": "10.201.19.2"
    },
    {
      "node": "guoning",
      "address": "10.10.1.150"
    }
  ]
}
```

**Comment by txfan** [comment]
Spring Cloud Consul uses application context id as service instance id by default. See https://github.com/spring-cloud/spring-cloud-consul/blob/v1.2.1.RELEASE/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/serviceregistry/ConsulAutoRegistration.java#L146

By adding `SPRING_APPLICATION_INSTANCE` and `spring.cloud.consul.discovery.instance-id` properties as below, this issue was resolved.

```
version: '3.2'
services:
  api:
    image: registry.example.com/example/example-api
    networks:
      - infra
   environment:
      - CI_ENVIRONMENT_SLUG=${CI_ENVIRONMENT_SLUG:-local}
      - CI_ENVIRONMENT_TIMEZONE=${CI_ENVIRONMENT_TIMEZONE:-Asia/Shanghai}
      - SPRING_APPLICATION_NAME=example-api
      - SPRING_APPLICATION_INSTANCE={{.Task.Slot}}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-debug}
      - SPRING_CLOUD_CONFIG_LABEL=${SPRING_CLOUD_CONFIG_LABEL:-master}
    volumes:
      - ./bootstrap.properties:/app/bootstrap.properties
```

bootstrap.properties
```properties
spring.cloud.consul.host=10.201.15.2
spring.cloud.consul.discovery.instance-id=${spring.application.name}-${spring.application.instance}
```
