### ISSUE TITLE
AWS retry join doesn't seem to work on 1.0. (Connects to self and then dies)

### ISSUE THREAD

**Issue by rlewkowicz** [hashicorp/consul#3666]
When filing a bug, please include the following:

### `consul version` for both Client and Server
```
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v1.0.0'
           Node ID: 'b2135b62-6d07-59e2-b5f0-3d8713009049'
         Node name: 'docker-swarm1-manager1'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, DNS: 8600)
      Cluster Addr: 172.31.30.188 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false
```
It's the latest docker container. Bound to host an an iam server.

### `consul info` for both Client and Server
Server:
```
swarm: docker exec a947d285f184 consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 51ea240
	version = 1.0.0
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 
	server = true
raft:
	applied_index = 0
	commit_index = 0
	fsm_pending = 0
	last_contact = never
	last_log_index = 0
	last_log_term = 0
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = []
	latest_configuration_index = 0
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 0
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 72
	max_procs = 2
	os = linux
	version = go1.9.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
Ubuntu 16.04, docker swarm, latest docker container (4 nodes) 

### Description of the Issue (and unexpected/desired result
I bring it up, and as I was reading your docs and tutorials, they should find each other elect a leader and be golden. It works perfectly if I select a master ip, the aws tags just dont seem to work.

### Reproduction steps
I use rex ray for dynamic ebs allocation so every node gets a fresh drive on deploy. I have tried the command line switches and they seem to do the same thing, just nothing. 

```
services:
  consul:
    image: consul
    volumes:
      - "consuldataebs:/tmp/consuldata"
    networks:
      - outside
    environment:
      - 'CONSUL_LOCAL_CONFIG={ "skip_leave_on_interrupt": true, "retry_join": ["provider=aws tag_key=ice-consul-host tag_value=ice-consul-host region=%REGION% access_key_id=%ACCESS_KEY_ID% secret_access_key=%SECRET_ACCESS_KEY%"] }'
    deploy:
      replicas: 4
    entrypoint:
      - consul
      - agent
      - -server
      - -data-dir=/tmp/consuldata
      - -bind={{ GetInterfaceIP "eth0" }}
      - -client=0.0.0.0
      - -bootstrap-expect=4
      - -log-level=DEBUG
```

### Log Fragments or Link to [gist](https://gist.github.com/)

https://gist.github.com/rlewkowicz/2ad00500c465d4c15d9eb291d9ea9371

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

Output with debug seems to be the same as trace
