### ISSUE TITLE
Failing TTL proxy health for Consul Connect with Kubernetes

### ISSUE THREAD

**Issue by tjsousa** [hashicorp/consul#4313]
#### Overview of the Issue

I'm trying to run a consul connect sidecar proxy with kubernetes services to try out the proxy funcionality without having to change existing services.

The error I'm seeing is:
`2018/06/29 14:36:30 [WARN] proxy: heartbeat failed: Unexpected response code: 500 (CheckID "db-proxy-ttl" does not have associated TTL)`

The "db" service is being registering through CLI with:
`consul connect proxy -service db -service-addr localhost:27017 -listen :9998 -register`

#### Reproduction Steps

Steps to reproduce this issue:

1. Deploy a consul cluster in Kubernetes
2. Deploy a service with a sidecar process registering the service
3. View 500 error in consul proxy health check

### Service + Sidecar Kubernetes manifest

```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data-rs0-1
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server|nfs-ip
    path: "/mongodb-volume-name"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-data-rs0-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc-rs01
  labels:
    app: myapp
    databaseVendor: mongo
    instanceType: dev
spec:
  type: LoadBalancer
  ports:
  - name: mongo-port
    port: 27017
    targetPort: 27017
    nodePort: 30017
    protocol: TCP
  selector:
    app: myapp
    databaseVendor: mongo
    instanceType: dev
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: dev-mongo-rc1
  labels:
    name: dev-mongo-rc1
spec:
  replicas: 1
  selector:
    app: myapp
    databaseVendor: mongo
    instanceType: dev
  template:
    metadata:
      labels:
        app: myapp
        databaseVendor: mongo
        instanceType: dev
        name: dev-mongo
        instance: dev-mongo
    spec:
      volumes:
      - name: mongodb-data-rs0-1
        persistentVolumeClaim:
          claimName: mongodb-data-rs0-1
      containers:
      - name: dev-mongo-rc1
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data-rs0-1
          mountPath: /data/db
      - name: consul-proxy
        image: "consul:1.2.0"
        ports:
        - containerPort: 9998
        command: ["consul"]
        args: ["connect", "proxy", "-service", "db", "-service-addr", "localhost:27017", "-listen", ":9998", "-register", "-http-addr", "sec-consul:8500"]
```

I'm not sure why is the health check failing for the proxy process, or where can I specify the requested TTL. Is this an intended usage for the proxy process, specially with Kubernetes?
