### ISSUE TITLE
v1.2.0+ trying to connect to CA when Connect protocol is disabled

### ISSUE THREAD

**Issue by pztrn** [hashicorp/consul#4421]
That's my setup:

1. Kubernetes (minikube on my machine).
2. 3 Consul instances successfully clustered, from consul:1.2.1 image.
3. Configuration:
```json
{
    "connect": {
        "enabled": false
    },
    "encrypt_verify_incoming": false,
    "encrypt_verify_outgoing": false,
    "log_level": "trace",
    "performance": {
        "raft_multiplier": 1
    },
    "verify_incoming": false,
    "verify_incoming_rpc": false,
    "verify_outgoing": false,
    "verify_server_hostname": false
}
```

4. Using github.com/hashicorp/consul/api like this: 
```go
func (s *Service) RegisterAtConsul(port int, versionMajor string, versionFull string, registerHealthCheck bool) error {
    s.versionFull = versionFull
    s.versionFullDashes = strings.Replace(s.versionFull, ".", "-", -1)
    s.versionMajor = versionMajor

    // Register with consul with only major version.
    agent := s.Client.Agent()
    serviceMajorVersion := &api.AgentServiceRegistration{
        Name:    s.Name + "-" + s.versionMajor,
        Tags:    s.Tags,
        Address: s.localIP,
        Port:    port,
    }

    serviceMajorVersion.ID = s.ID + "-" + s.versionMajor

    if registerHealthCheck {
        serviceMajorVersion.Check = &api.AgentServiceCheck{
            Name:     serviceMajorVersion.ID + " HTTP check",
            HTTP:     "http://" + s.localIP + ":" + strconv.Itoa(port) + "/api/v1/healthCheck/",
            Method:   http.MethodPost,
            Interval: "5s",
            Timeout:  "2s",
        }
    }

    err := agent.ServiceRegister(serviceMajorVersion)
    if err != nil {
        return err
    }

    // Register at consul with full version.
    serviceFullVersion := &api.AgentServiceRegistration{
        Name:    s.Name + "-" + s.versionFullDashes,
        Tags:    s.Tags,
        Address: s.localIP,
        Port:    port,
    }

    serviceFullVersion.ID = s.ID + "-" + s.versionFullDashes

    if registerHealthCheck {
        serviceFullVersion.Check = &api.AgentServiceCheck{
            Name:     serviceFullVersion.ID + " HTTP check",
            HTTP:     "http://" + s.localIP + ":" + strconv.Itoa(port) + "/api/v1/healthCheck/",
            Method:   http.MethodPost,
            Interval: "5s",
            Timeout:  "2s",
        }
    }

    err1 := agent.ServiceRegister(serviceFullVersion)
    if err1 != nil {
        return err1
    }

    return nil
}
```

Where s.Client - from api.NewClient().

I haven't created AgentServiceConnect structures, do I think it should be disabled by default.

Everything works, service registers and address can be reached via HTTP or DNS requests. The problem with CA bootstraping which I want to disable, as Consul cluster runs in private environment without internet access. On service registering and de-registering it executes a request which push back this error:

2018/07/17 09:45:30 [ERR] http: Request GET /v1/agent/connect/ca/leaf/test-192.168.137.144, error: cluster has no CA bootstrapped from=192.168.99.1:54062

After first message appeared it starts to eat 100-150% CPU of 4-core host constantly.

consul info output from master (which eats CPU):

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 39f93f01
        version = 1.2.1
consul:
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = 172.20.0.4:8300
        server = true
raft:
        applied_index = 146
        commit_index = 146
        fsm_pending = 0
        last_contact = 0
        last_log_index = 146
        last_log_term = 2
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:3634851e-5b58-d0ad-3f22-546de4d294c5 Address:172.20.0.4:8300} {Suffrage:Voter ID:ee5204e4-2a30-f83f-3dde-6c2e0d46902d Address:172.20.0.5:8300} {Suffrage:Voter ID:27a3b189-89e6-ec95-0177-003b023fdefb Address:172.20.0.6:8300}]
        latest_configuration_index = 1
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 12433
        max_procs = 2
        os = linux
        version = go1.10.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 4
        members = 3
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 5
        members = 3
        query_queue = 0
        query_time = 1
```

Complete log for register-deregister with TRACE level:

```
2018/07/17 10:05:07 [ERR] http: Request GET /v1/agent/connect/ca/leaf/test-192.168.137.144, error: cluster has no CA bootstrapped from=192.168.99.1:54892
2018/07/17 10:05:07 [ERR] http: Request GET /v1/agent/connect/ca/leaf/test-192.168.137.144, error: cluster has no CA bootstrapped from=192.168.99.1:54888
2018/07/17 10:05:07 [INFO] agent: Synced service "test-192.168.137.144-0"
2018/07/17 10:05:08 [INFO] agent: Synced service "test-192.168.137.144-0-1-1"
2018/07/17 10:05:09 [INFO] agent: Deregistered service "test-192.168.137.144-0"
2018/07/17 10:05:09 [INFO] agent: Deregistered service "test-192.168.137.144-0-1-1"
2018/07/17 10:05:09 [ERR] http: Request GET /v1/agent/connect/ca/leaf/test-192.168.137.144, error: cluster has no CA bootstrapped from=192.168.99.1:54902
2018/07/17 10:05:10 [INFO] agent: Synced service "test-192.168.137.144-0"
2018/07/17 10:05:11 [INFO] agent: Synced service "test-192.168.137.144-0-1-1"
2018/07/17 10:05:11 [INFO] agent: Deregistered service "test-192.168.137.144-0"
2018/07/17 10:05:12 [INFO] agent: Deregistered service "test-192.168.137.144-0-1-1"
2018/07/17 10:05:12 [ERR] http: Request GET /v1/agent/connect/ca/leaf/test-192.168.137.144, error: cluster has no CA bootstrapped from=192.168.99.1:54888
2018/07/17 10:05:12 [ERR] http: Request GET /v1/agent/connect/ca/leaf/test-192.168.137.144, error: cluster has no CA bootstrapped from=192.168.99.1:54886
2018/07/17 10:05:12 [ERR] http: Request GET /v1/agent/connect/ca/leaf/test-192.168.137.144, error: cluster has no CA bootstrapped from=192.168.99.1:54908
2018/07/17 10:05:13 [INFO] agent: Synced service "test-192.168.137.144-0"
2018/07/17 10:05:13 [INFO] agent: Synced service "test-192.168.137.144-0-1-1"
2018/07/17 10:05:14 [INFO] agent: Deregistered service "test-192.168.137.144-0"
2018/07/17 10:05:14 [INFO] agent: Deregistered service "test-192.168.137.144-0-1-1"
```

Configuration for Kubernetes:

1. Service definition:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    name: consul
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: https
      port: 8443
      targetPort: 8443
    - name: rpc
      port: 8400
      targetPort: 8400
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
      targetPort: 8302
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
      targetPort: 8302
    - name: server
      port: 8300
      targetPort: 8300
    - name: consuldns
      port: 8600
      targetPort: 8600
  selector:
    app: consul
```

2. StatefulSet definition:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
spec:
  serviceName: consul
  replicas: 3
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      #affinity:
      #  podAntiAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      - labelSelector:
      #          matchExpressions:
      #            - key: app
      #              operator: In
      #              values:
      #                - consul
      #        topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: consul
          image: "consul:1.2.1"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "agent"
            - "-advertise=$(POD_IP)"
            - "-bind=0.0.0.0"
            - "-bootstrap-expect=3"
            - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local"
            - "-client=0.0.0.0"
            - "-config-file=/consul/myconfig/config.json"
            - "-datacenter=dc1"
            - "-data-dir=/consul/mydata"
            - "-server"
            - "-ui"
            - "-disable-host-node-id"
          volumeMounts:
            - name: data
              mountPath: /consul/mydata
            - name: config
              mountPath: /consul/myconfig
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - consul leave
          ports:
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: alt-port
            - containerPort: 53
              name: udp-port
            - containerPort: 8443
              name: https-port
            - containerPort: 8080
              name: http-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8600
              name: consuldns
            - containerPort: 8300
              name: server
      volumes:
        - name: config
          configMap:
            name: consul
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
```

Cluster was created with these commands:

```
kubectl create configmap consul --from-file=config.json=server.json
kubectl create -f service.yaml
kubectl create -f statefulset-dev.yaml
```
