### ISSUE TITLE
Feature Request: configuration file in k/v with a query to vault

### ISSUE THREAD

**Issue by gabrielfsousa** [hashicorp/consul#4705]
#### Feature Description

configuration file in k/v with a query to vault

#### Use Case(s)

file on K/V 
```
 datasource:
                url: jdbc:postgresql://url:5550/context-root 
                name: 
                username: {{$query-vault-secret.Data.username}}
                password: {{$query-vault-secret.Data.password}}
```
