### ISSUE TITLE
Using LoadAssignment doesn't work for tcp_proxy target for some reason.

### ISSUE THREAD

**Issue by dio** [hashicorp/consul#4853]
From my code reading here: https://github.com/hashicorp/consul/blob/master/agent/xds/clusters.go#L44, I'm interested to observe the following comment:

```
// API v2 docs say hosts is deprecated and should use LoadAssignment as
// below.. but it doesn't work for tcp_proxy target for some reason.
```

@banks do we have a test covering https://github.com/hashicorp/consul/blob/master/agent/xds/clusters.go#L44? I'd like to investigate from envoy side, why this is happening. 

Thanks!

**Comment by dio** [comment]
I tried to manually running envoy with the following config:

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.tcp_proxy
              config:
                stat_prefix: ingress_tcp
                cluster: service_local

  clusters:
    - name: service_local
      connect_timeout: 0.25s
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: service_local
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: localhost
                      port_value: 1337
```

And ran an echo server (node), 

```js
var net = require('net');

var server = net.createServer(function(socket) {
  socket.write('Echo server\r\n');
  socket.pipe(socket);
});

server.listen(1337, '127.0.0.1');
```

Then connected a telnet session to envoy (port 10000). It seems OK.

**Comment by banks** [comment]
@dio interesting thanks.

I was testing against envoy 1.7.1 if it helps here. There is a low-level test of the envoy config generated by that function but it's obviously expecting the current output that I managed to get working. I don't have automated end-to-end tests that actually validate the envoy consumes the config and behaves as expected yet.

My understanding though from the docs is that just removing the Hosts line below that comment and uncommenting the rest of that block _should_ work. Yet I could never get the tcp proxy to recognize the update. I may have missed something or been calling it wrong of course but after some trial and error I went with what seemed to work right for now. I have a short list of things to iron out with Envoy in the next few weeks to see where I went wrong/if changes are needed to Envoy to accommodate 😄 .

Could it be because I made it `Cluster_STATIC`? The `LoadAssignment` syntax worked fine for the upstream listeners which are also TCPProxy filters coming to think of it, but they are delivered via EDS instead of being delivered as "Static" cluster from CDS?

**Comment by dio** [comment]
> Yet I could never get the tcp proxy to recognize the update. I may have missed something or been calling it wrong of course but after some trial and error I went with what seemed to work right for now

Interesting, will try to poke around.

> I have a short list of things to iron out with Envoy in the next few weeks to see where I went wrong/if changes are needed to Envoy to accommodate

Sure @banks I'd love to help if that's possible. 

> Could it be because I made it Cluster_STATIC? The LoadAssignment syntax worked fine for the upstream listeners which are also TCPProxy filters coming to think of it, but they are delivered via EDS instead of being delivered as "Static" cluster from CDS?

This. I want to test. will update you about it.

**Comment by diorahman** [comment]
@banks 

Do you mean you're sending an LDS response e.g. 

```yaml
resources:
  - '@type': type.googleapis.com/envoy.api.v2.Listener
    name: ingress
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
      - filters:
          - name: envoy.tcp_proxy
            config:
              stat_prefix: ingress_tcp
              cluster: service1
```

And the corresponding CDS response, e.g.

```yaml
resources:
  - '@type': 'type.googleapis.com/envoy.api.v2.Cluster'
    name: service1
    connect_timeout: 0.25s
    type: STATIC
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service1
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 1337
```

And it doesn't work?

**Comment by dio** [comment]
@banks 

Do you mean you're sending an LDS response e.g. 

```yaml
resources:
  - '@type': type.googleapis.com/envoy.api.v2.Listener
    name: ingress
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
      - filters:
          - name: envoy.tcp_proxy
            config:
              stat_prefix: ingress_tcp
              cluster: service1
```

And the corresponding CDS response, e.g.

```yaml
resources:
  - '@type': 'type.googleapis.com/envoy.api.v2.Cluster'
    name: service1
    connect_timeout: 0.25s
    type: STATIC
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service1
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 1337
```

And it doesn't work?
