### ISSUE TITLE
DNS resolving with ACL and multi datacenter architecture

### ISSUE THREAD

**Issue by witalisoft** [hashicorp/consul#5076]
#### Overview of the Issue

In multi datacenter installation with ACL each agent should resolve dns name properly, but in non primary_datacenter (ACL) agent is flapping with dns resolving:
```
$ curl http://consul.service.consul
curl: (6) Could not resolve host: consul.service.consul
$ curl http://consul.service.consul
curl: (7) Failed to connect to consul.service.consul port 80: Connection refused
```
when I switch to resolve name to IPv4 it starts working:
```
$ curl http://consul.service.consul -4
curl: (7) Failed to connect to consul.service.consul port 80: Connection refused
$ curl http://consul.service.consul -4
curl: (7) Failed to connect to consul.service.consul port 80: Connection refused
```

In primary_datacenter everything works fine. When I disable ACL it also starts working fine.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster using docker-compose:
```
version: '3'

services:

  dc1-consul-server-1: &consul-server
    image: consul:1.4.0
    volumes:
      - ./config:/etc/consul
    networks:
      - consul-demo
    command: "agent -config-file=/etc/consul/agent.hcl -datacenter dc1 -server -bootstrap-expect 1 \
              -retry-join-wan 'dc2-consul-server-2'"
    hostname: dc1-consul-server-1

  dc2-consul-server-1:
    <<: *consul-server
    command: "agent -config-file=/etc/consul/agent.hcl -datacenter dc2 -server -bootstrap-expect 1 \
              -retry-join-wan 'dc1-consul-server-1'"
    hostname: dc2-consul-server-1

networks:
  consul-demo:
```
2. Use agent.hcl configuration:
```
primary_datacenter = "dc1"
acl = {
	enabled = true
	default_policy = "deny"
	down_policy = "e
```
3. Set ACL:
Agent token with policy:
```
node_prefix "" { policy = "write" } service_prefix "" { policy = "read" }
```

Anonymous token with policy:
```
node_prefix "" { policy = "read" }
service_prefix "" { policy = "read" }
```
### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease =
	revision = 0bddfa23
	version = 1.4.0
consul:
	acl = enabled
	bootstrap = true
	known_datacenters = 2
	leader = true
	leader_addr = 10.102.1.202:8300
	server = true
raft:
	applied_index = 90238
	commit_index = 90238
	fsm_pending = 0
	last_contact = 0
	last_log_index = 90238
	last_log_term = 35
	last_snapshot_index = 81927
	last_snapshot_term = 35
	latest_configuration = [{Suffrage:Voter ID:6d338f86-ad2e-9fd2-0330-bf20ff324854 Address:10.102.1.202:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 35
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 105
	max_procs = 1
	os = linux
	version = go1.11.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 1
	event_time = 35
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 46
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 53
	members = 4
	query_queue = 0
	query_time = 1
```

</details>

### Log Fragments

```
    2018/12/07 07:57:05 [DEBUG] consul: dropping node "dc2-consul-server-1" from result due to ACLs
consul: dropping node "dc2-consul-server-1" from result due to ACLs
    2018/12/07 07:57:05 [DEBUG] dns: request for name consul.service.consul. type AAAA class IN (took 30.666641ms) from client 10.116.1.101:25897 (udp)
dns: request for name consul.service.consul. type AAAA class IN (took 30.666641ms) from client 10.116.1.101:25897 (udp)
    2018/12/07 07:57:05 [DEBUG] dns: request for name consul.service.consul. type A class IN (took 58.136411ms) from client 10.116.1.101:30060 (udp)
dns: request for name consul.service.consul. type A class IN (took 58.136411ms) from client 10.116.1.101:30060 (udp)
    2018/12/07 07:57:06 [DEBUG] consul: dropping node "dc2-consul-server-1" from result due to ACLs```
