### ISSUE TITLE
Consul Connect - Ability to configure envoy access_log_path

### ISSUE THREAD

**Issue by prashantchari** [hashicorp/consul#5231]
#### Feature Description

The access_log_path for Envoy currently defaults to /dev/null. It'd be great if this was configurable with Consul Connect.

#### Use Case(s)

Output envoy access logs to stdout or saving them to a local file.

**Comment by mkeeler** [comment]
Reopening to capture that we want to be able to configure the access log path for both the TCPProxy filters and the HTTP Connect Manager within the xDS package in addition to the access logs for the admin interface.

**Comment by akhayyat** [comment]
Is there really no way today to enable and/or configure access logs for Envoy sidecars using Consul Connect?

**Comment by alkalinecoffee** [comment]
I don't think there is a way to simply pass in an access log endpoint other than `/dev/null` through native Consul config (although I think you can for admin logs, oddly enough).

However, there may be a way to pass it in using a Consul [escape hatch](https://www.consul.io/docs/connect/proxies/envoy.html#escape-hatch-overrides) which allows you to pass in custom Envoy-specific configuration directly to Envoy.

Using native Envoy configuration, this filter would send access logs to `/dev/stdout`:

```yaml
static_resources:
  listeners:
  - name: inbound_10000
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    traffic_direction: INBOUND
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          access_log:
          - name: envoy.access_loggers.file
            config:
              path: /dev/stdout
```

The escape hatch override config values map to a bootstrap template which is used to build the Envoy configuration file.  You can find the template here:  https://github.com/hashicorp/consul/blob/master/command/connect/envoy/bootstrap_tpl.go.  You can also provide your own custom Envoy template using this same pattern and push standard log configurations to all of your proxies.
