### ISSUE TITLE
Consul not working with nodejs

### ISSUE THREAD

**Issue by pwyssmuller** [hashicorp/consul#5372]
Good evening,

I've been trying desperately to get nodejs to work with consul without success. I believe all my consul and nginx settings are fine. I added a flask application to the mix for testing and it works just fine. 

The flask applications (event) endpoint is /events/v1 and I can get a 200 response via 192.168.99.102/events/v1.
The nodejs applications (user) endpoint is /api and I can only get a 200 response via 192.168.99.102:3000/api. (with the 3000 port)
Accessing the node app via 192.168.99.102/api always gives me a 404. 

Here is my nginx config (created with consul template)

```
upstream consul {
    zone upstream-consul 64k;
    least_conn;
    server 192.168.99.102:8300 max_fails=3 fail_timeout=60 weight=1;

}
upstream event {
    zone upstream-event 64k;
    least_conn;
    server 172.18.0.6:5000 max_fails=3 fail_timeout=60 weight=1;

}
upstream user {
    zone upstream-user 64k;
    least_conn;
    server 172.18.0.5:3000 max_fails=3 fail_timeout=60 weight=1;
}

server {
    listen 80 default_server;

    location / {
        root /usr/share/nginx/html/;
        index index.html;
    }

    location /nginx_status {
        stub_status;
    }

    location /consul {
        proxy_pass http://consul;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_connect_timeout 600;
        proxy_send_timeout 600;
        proxy_read_timeout 600;
        send_timeout 600;
    }

    location /event {
        proxy_pass http://event;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_connect_timeout 600;
        proxy_send_timeout 600;
        proxy_read_timeout 600;
        send_timeout 600;
    }

    location /user {
        proxy_pass http://user;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_connect_timeout 600;
        proxy_send_timeout 600;
        proxy_read_timeout 600;
        send_timeout 600;
    }
}
```

my docker-compose file looks like this:
```
version: '3'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    links:
      - consul
    labels:
      SERVICE_IGNORE: 'yes'
    ports:
      - "80:80"
    depends_on:
      - registrator

  consul:
    command: -server -bootstrap-expect 1 -advertise ${HOST_IP}
    image: progrium/consul
    container_name: consul
    labels:
      SERVICE_IGNORE: 'yes'
    ports:
      - "8500:8500"

  registrator:
    command: "-internal consul://consul:8500"
    image: gliderlabs/registrator:latest
    container_name: registrator
    links:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
      - consul
      
  user:
    restart: unless-stopped
    build: ./userservice
    container_name: user
    working_dir: /app/
    command: node /app/index.js
    expose: 
        - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./userservice/:/app/
    labels:
      SERVICE_NAME: user
      SERVICE_3000_CHECK_HTTP: /health
      SERVICE_3000_CHECK_INTERVAL: 5s
      SERVICE_TAGS: microservice
    environment:
      - SERVICE_NAME=user
      - CONSUL_AGENT_URL=${HOST_IP}
      - CONSUL_AGENT_PORT=8500
    depends_on:
      - nginx
      
  event:
    restart: unless-stopped
    build: ./eventservice
    container_name: event
    working_dir: /usr/local/app/
    command: python run.py
    # command: [ "uwsgi", "--ini", "local.ini:event-service" ] #use this for production
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}/eventservice/:/usr/local/app/
      - ${PWD}/eventservice/export/:/export/
    labels:
      SERVICE_NAME: event
      SERVICE_5000_CHECK_HTTP: /health
      SERVICE_5000_CHECK_INTERVAL: 15s
      SERVICE_TAGS: microservice
    environment:
      - SERVICE_NAME=event
      - CONSUL_AGENT_URL=${HOST_IP}
      - CONSUL_AGENT_PORT=8500
      - PYTHONUNBUFFERED=1
    depends_on:
      - nginx
```

Last but not least, my nodejs application code:
```
const express = require('express');
var ip = require('ip');

const app = express();

app.get('/api', (req, res) => {
    console.log("## API called !!");
    res.send('Hey NODEJS single user!');
});

app.get('/health', (req, res) => {
    console.log("health check from", ip.address());
    res.sendStatus(200)
});


app.listen(3000, function () {
  console.log('\r\n * Node.js API listening on ' + ip.address() + ':3000! * \r\n');
});
```

Any help is truly appreciated.
