### ISSUE TITLE
Spurious failures of cross-DC requests

### ISSUE THREAD

**Issue by nahratzah** [hashicorp/consul#5595]
#### Overview of the Issue

Cross-datacenter requests sometimes fail, due to consul selecting a decommissioned server as its target.

We suspect this leads to failed KV requests, as well as DNS being super slow.

##### 1: create a set of consul clusters

Using the docker `consul:1.2.3` image, create *4* consul clusters each with *5* servers.
```
docker-compose up -d --scale consul_nodes_dc1=4 --scale consul_nodes_dc2=4 --scale consul_nodes_dc3=4 --scale consul_nodes_dc4=4 --scale consul_nodes_dc5=4
```

<details>
*docker-compose.yml*:
```
version: "2"
services:
  consul_dc1:
    image: consul:1.2.3
    command: "agent -ui -server -client 0.0.0.0 -datacenter=dc1 -bootstrap-expect=5 -join consul_dc1"
  consul_nodes_dc1:
    image: consul:1.2.3
    command: "agent -server -bootstrap-expect=5 -datacenter=dc1 -join consul_dc1"
    depends_on:
      - consul_dc1
  consul_dc2:
    image: consul:1.2.3
    command: "agent -server -bootstrap-expect=5 -datacenter=dc2 -join consul_dc2"
  consul_nodes_dc2:
    image: consul:1.2.3
    command: "agent -server -bootstrap-expect=5 -datacenter=dc2 -join consul_dc2"
    depends_on:
      - consul_dc2
  consul_dc3:
    image: consul:1.2.3
    command: "agent -server -bootstrap-expect=5 -datacenter=dc3 -join consul_dc3"
  consul_nodes_dc3:
    image: consul:1.2.3
    command: "agent -server -bootstrap-expect=5 -datacenter=dc3 -join consul_dc3"
    depends_on:
      - consul_dc3
  consul_dc4:
    image: consul:1.2.3
    command: "agent -server -bootstrap-expect=5 -datacenter=dc4 -join consul_dc4"
  consul_nodes_dc4:
    image: consul:1.2.3
    command: "agent -server -bootstrap-expect=5 -datacenter=dc4 -join consul_dc4"
    depends_on:
      - consul_dc4
  tribute:
    image: tribute
```
</details>

##### 2: WAN join all these clusters

```
docker exec docker_consul_dc2_1 /bin/consul join -wan consul_dc1
docker exec docker_consul_dc3_1 /bin/consul join -wan consul_dc1
docker exec docker_consul_dc4_1 /bin/consul join -wan consul_dc1
```

##### 3: create a KV in each cluster, for use later

```
for dc in dc1 dc2 dc3 dc4; do docker exec docker_consul_${dc}_1 /bin/consul kv put foobar "kv in ${dc}"; done
```

##### 4: cycle through the nodes, creating lots and lots of failed nodes in the process

```
for x in {1,2,3,4,5,6}{1,2,3,4,5,6,7,8,9,0} ; do ./cycle.sh ; done
```

Note that we leave `dc1` untouched, only affecting `dc2`, `dc3`, and `dc4`.

<details>
cycle.sh contents:

    #!/bin/bash

    for dc in dc2 dc3 dc4; do
      let "tribute_scale_count = 1 + $(docker-compose ps | grep -c tribute)"
      docker-compose scale consul_nodes_${dc}=3
      sleep 10
      docker-compose scale tribute=${tribute_scale_count}
      sleep 10
      docker-compose scale consul_nodes_${dc}=4
      sleep 10
    done
</details>

##### 5: Leave to simmer for 2+ days, while repeatedly querying the clusters

We collect the query log, because disk space is cheap.
(Use tmux so you can detach.)
```
while sleep 5; do ./query.sh ; done 2>&1 | tee query.log
```

<details>
query.sh contents:
    #!/bin/bash

    for origin_dc in dc1 dc2 dc3 dc4 ; do
      for target_dc in dc1 dc2 dc3 dc4 dc5; do
        docker exec docker_consul_${origin_dc}_1 /bin/consul kv get -datacenter=${target_dc} foobar
      done
    done
</details>

##### 6: Observe spurious failure

```
docker-compose logs | grep 'rpc error: lead thread didn'\''t get connection'
```

Note, it took a couple of days for us to generate the log messages.
Have patience. <3

Also note the number of `500` HTTP statuses in `query.log`:
```
grep 500 query.log
```

### Operating system and Environment details

`uname -a`: `Linux z-kube-beach-avandersteldt-penguin 4.4.0-1077-aws #87-Ubuntu SMP Wed Mar 6 00:03:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

`consul-1.2.3`

### Log Fragments

Output from step 5:
```
consul_dc4_1        |     2019/03/29 14:12:45 [ERR] consul: RPC failed to server 172.19.0.33:8300 in DC "dc2": rpc error getting client: failed to get conn: rpc error: lead thread didn't get connection
consul_dc4_1        |     2019/03/29 14:12:45 [ERR] http: Request GET /v1/kv/foobar?dc=dc2, error: rpc error getting client: failed to get conn: rpc error: lead thread didn't get connection from=127.0.0.1:57878
consul_dc2_1        |     2019/03/29 14:37:38 [ERR] consul: RPC failed to server 172.19.0.77:8300 in DC "dc4": rpc error getting client: failed to get conn: rpc error: lead thread didn't get connection
consul_dc2_1        |     2019/03/29 14:37:38 [ERR] http: Request GET /v1/kv/foobar?dc=dc4, error: rpc error getting client: failed to get conn: rpc error: lead thread didn't get connection from=127.0.0.1:52206
```
