### ISSUE TITLE
Leader still elected when below quorum

### ISSUE THREAD

**Issue by donaltuohy** [hashicorp/consul#5947]
#### Overview of the Issue

Hello. We are having a problem with our consul cluster deployed in Kubernetes. We are using consul as a key value store and consul templates is watching this kv store for changes. Our cluster has five agent servers. From our understanding, the servers should be unavailable when there is less than 3 servers up (N/2 +1). This is not the case for our cluster however. When the cluster is scaled down to 1 or 2 nodes, we are still able to perform read and write operations on the KV Store. When the cluster is scaled down to just 2 servers, it is still able to elect a leader.

#### Checking peers list
Calling `consul operator raft list-peers` when all 5 nodes are up:
```
Node           ID                                    Address              State     Voter  RaftProtocol
consul-4  10db205a-10ea-7613-9b49-5e98d51d52cc  172.22.45.229:8300   leader    true   3
consul-1  bfb0b177-77ae-807e-b379-7d68e10e1e00  172.22.33.53:8300    follower  true   3
consul-3  6edca10e-e2af-6e2c-4e7c-c8b3102aa734  172.22.128.243:8300  follower  true   3
consul-2  c129b4f6-7a41-bf62-7537-addad559fce2  172.22.72.93:8300    follower  true   3
consul-0  f6f3b9ab-db3b-12fd-4242-9648925a0d3f  172.22.167.223:8300  follower  true   3
```

Calling `consul operator raft list-peers` when only 2 nodes are up:
```
Node           ID                                    Address              State     Voter  RaftProtocol
consul-1  bfb0b177-77ae-807e-b379-7d68e10e1e00  172.22.33.53:8300    leader    true   3
consul-0  f6f3b9ab-db3b-12fd-4242-9648925a0d3f  172.22.167.223:8300  follower  true   3
```

As you can see here, consul-4 was the leader before the cluster was scaled down. Once it was scaled down, consul-1 was able to be elected as leader. Even though there was only two nodes in the cluster. 

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with 5 server nodes with the configuration specified below
2. Scale the cluster down to only 1 or 2 server nodes.
3. A leader will still be elected and read and write operations are still possible.

### Consul info for Server

<details>
  <summary>Server info</summary>

```
agent:
    check_monitors = 0
    check_ttls = 0
    checks = 0
    services = 0
build:
    prerelease =
    revision = 0bddfa23
    version = 1.4.0
consul:
    acl = disabled
    bootstrap = false
    known_datacenters = 1
    leader = false
    leader_addr = 172.22.33.53:8300
    server = true
raft:
    applied_index = 1863915
    commit_index = 1863915
    fsm_pending = 0
    last_contact = 41.567589ms
    last_log_index = 1863915
    last_log_term = 1480
    last_snapshot_index = 1852126
    last_snapshot_term = 1477
    latest_configuration = [{Suffrage:Voter ID:bfb0b177-77ae-807e-b379-7d68e10e1e00 Address:172.22.33.53:8300} {Suffrage:Voter ID:f6f3b9ab-db3b-12fd-4242-9648925a0d3f Address:172.22.167.223:8300} {Suffrage:Voter ID:c129b4f6-7a41-bf62-7537-addad559fce2 Address:172.22.72.93:8300} {Suffrage:Voter ID:6edca10e-e2af-6e2c-4e7c-c8b3102aa734 Address:172.22.160.60:8300} {Suffrage:Voter ID:10db205a-10ea-7613-9b49-5e98d51d52cc Address:172.22.44.206:8300}]
    latest_configuration_index = 1863909
    num_peers = 4
    protocol_version = 3
    protocol_version_max = 3
    protocol_version_min = 0
    snapshot_version_max = 1
    snapshot_version_min = 0
    state = Follower
    term = 1480
runtime:
    arch = amd64
    cpu_count = 48
    goroutines = 897
    max_procs = 48
    os = linux
    version = go1.11.1
serf_lan:
    coordinate_resets = 0
    encrypted = true
    event_queue = 0
    event_time = 16
    failed = 0
    health_score = 0
    intent_queue = 0
    left = 0
    member_time = 3530
    members = 5
    query_queue = 0
    query_time = 1
serf_wan:
    coordinate_resets = 0
    encrypted = true
    event_queue = 0
    event_time = 1
    failed = 0
    health_score = 0
    intent_queue = 0
    left = 0
    member_time = 2453
    members = 5
    query_queue = 0
    query_time = 1
```

</details>

### Operating system and Environment details

This cluster is deployed in Kubernetes. Here is the consul.yaml file:

<details>
    <summary>Kubernetes configuration</summary>

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
  labels:
    team: team-name
    project: consul
    role: consul
spec:
  serviceName: consul
  replicas: 5
  updateStrategy:
    type: RollingUpdate
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
        project: consul
        role: consul
  template:
    metadata:
      labels:
        team: team-name
        project: consul
        role: consul
      annotations:
ad.datadoghq.com/consul.check_names: '["consul"]'
ad.datadoghq.com/consul.init_configs: '[{}]'
ad.datadoghq.com/consul.instances: '[{"url": "http://%%host%%:8500", "tags": "%%tags%%", "self_leader_check": "true", "network_latency_checks": "true"}]'
        secret/GOSSIP_ENCRYPTION_KEY: GOSSIP_ENCRYPTION_KEY
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: project
                    operator: In
                    values:
                      - consul
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: set-volume-permissions
          image: bash
          command: ["/bin/sh", "-c", "chown consul:consul /var/lib/consul"]
          volumeMounts:
            - name: consul-data
              mountPath: /var/lib/consul
      containers:
        - image: gcr.io/docker-images/apps/consul:latest
          name: consul
          imagePullPolicy: Always
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command: ["/bin/sh"]
          args:
            - '-c'
            - >
              su-exec consul:consul
              /bin/consul
              agent
              -advertise=$(POD_IP)
              -bind=0.0.0.0
              -bootstrap-expect=5
              -retry-join=consul-0.my-consul-cluster.${NAMESPACE}.svc.cluster.local
              -retry-join=consul-1.my-consul-cluster.${NAMESPACE}.svc.cluster.local
              -retry-join=consul-2.my-consul-cluster.${NAMESPACE}.svc.cluster.local
              -retry-join=consul-3.my-consul-cluster.${NAMESPACE}.svc.cluster.local
              -retry-join=consul-4.my-consul-cluster.${NAMESPACE}.svc.cluster.local
              -client=0.0.0.0
              -config-file=/consul/config/server.json
              -encrypt=$(cat /secrets/GOSSIP_ENCRYPTION_KEY)
              -datacenter=${NAMESPACE}
              -data-dir=/var/lib/consul
              -domain=cluster.local
              -server
              -ui
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - consul leave
          ports:
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: alt-port
            - containerPort: 53
              name: udp-port
            - containerPort: 8443
              name: https-port
            - containerPort: 8080
              name: http-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8600
              name: consuldns
            - containerPort: 8300
              name: server
          readinessProbe:
            httpGet:
              path: /v1/status/peers
              port: 8500
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - ps aux | grep consul
            initialDelaySeconds: 5
            timeoutSeconds: 2
          volumeMounts:
            - name: consul-data
              mountPath: /var/lib/consul
  volumeClaimTemplates:
  - metadata:
      name: consul-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "aws-ebs-gp2"
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    team: team-name
    project: consul
    role: consul
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: https
      port: 8443
      targetPort: 8443
    - name: rpc
      port: 8400
      targetPort: 8400
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
      targetPort: 8302
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
      targetPort: 8302
    - name: server
      port: 8300
      targetPort: 8300
    - name: consuldns
      port: 8600
      targetPort: 8600
  selector:
    project: consul
    role: consul

```

</details>

### Log Fragments
Logs from `consul-0` when the cluster is scaled from 5 servers to 1: 
```
2019/06/07 15:37:33 [INFO] serf: EventMemberLeave: consul-4.pod999 172.22.44.206
2019/06/07 15:37:33 [INFO] consul: Handled member-leave event for server "consul-4.pod999" in area "wan"
2019/06/07 15:37:36 [INFO] serf: EventMemberLeave: consul-4 172.22.44.206
2019/06/07 15:37:36 [INFO] consul: Removing LAN server consul-4 (Addr: tcp/172.22.44.206:8300) (DC: pod999)
2019/06/07 15:37:42 [WARN] raft: Rejecting vote request from 172.22.44.206:8300 since we have a leader: 172.22.33.53:8300
2019/06/07 15:37:50 [INFO] serf: EventMemberLeave: consul-3.pod999 172.22.160.60
2019/06/07 15:37:50 [INFO] consul: Handled member-leave event for server "consul-3.pod999" in area "wan"
2019/06/07 15:37:54 [INFO] serf: EventMemberLeave: consul-3 172.22.160.60
2019/06/07 15:37:54 [INFO] consul: Removing LAN server consul-3 (Addr: tcp/172.22.160.60:8300) (DC: pod999)
2019/06/07 15:38:02 [WARN] raft: Rejecting vote request from 172.22.160.60:8300 since we have a leader: 172.22.33.53:8300
2019/06/07 15:38:05 [INFO] serf: EventMemberLeave: consul-2.pod999 172.22.72.93
2019/06/07 15:38:05 [INFO] consul: Handled member-leave event for server "consul-2.pod999" in area "wan"
2019/06/07 15:38:09 [INFO] serf: EventMemberLeave: consul-2 172.22.72.93
2019/06/07 15:38:09 [INFO] consul: Removing LAN server consul-2 (Addr: tcp/172.22.72.93:8300) (DC: pod999)
2019/06/07 15:38:15 [WARN] raft: Rejecting vote request from 172.22.72.93:8300 since we have a leader: 172.22.33.53:8300
2019/06/07 15:38:22 [INFO] serf: EventMemberLeave: consul-1.pod999 172.22.33.53
2019/06/07 15:38:22 [INFO] consul: Handled member-leave event for server "consul-1.pod999" in area "wan"
2019/06/07 15:38:26 [INFO] serf: EventMemberLeave: consul-1 172.22.33.53
2019/06/07 15:38:26 [INFO] consul: Removing LAN server consul-1 (Addr: tcp/172.22.33.53:8300) (DC: pod999)
2019/06/07 15:38:31 [WARN] raft: Heartbeat timeout from "172.22.33.53:8300" reached, starting election
2019/06/07 15:38:31 [INFO] raft: Node at 172.22.167.223:8300 [Candidate] entering Candidate state in term 1481
2019/06/07 15:38:31 [INFO] raft: Election won. Tally: 1
2019/06/07 15:38:31 [INFO] raft: Node at 172.22.167.223:8300 [Leader] entering Leader state
2019/06/07 15:38:31 [INFO] consul: cluster leadership acquired
2019/06/07 15:38:31 [INFO] consul: New leader elected: consul-0
2019/06/07 15:38:31 [INFO] consul: member 'consul-1' left, deregistering
```

**Comment by banks** [comment]
Hi thanks for the issue.

I think I know what is going on here. It's because of this:

```
lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - consul leave
```

Performing a graceful leave on a server agent is saying "this server should no longer be considered part of the quorum" and explicitly reduces the quorum size. 

So when you scale the cluster down each server stops and gracefully exits, reconfiguring the quorum to be smaller.

This is why, by default, server agents **do not** leave the cluster when they are terminated so that they are just marked as "failed" until they come back and the other servers still consider them part of the quorum. The default for _client_ agents is to always leave on terminate since that is generally the intention and there is no harm in doing so on the cluster.

Can you remove that preStop hook and test again - I think it will restore the behaviour you expect. I'll close the issue if so as this is expected behaviour.
