### ISSUE TITLE
Docker-compose consul

### ISSUE THREAD

**Issue by iwanhsky** [hashicorp/consul#6233]
Hello everyone.

We used the Windows Containers openjdk image:8-nanoserver and consul for Windows Server image: stefanscherer/consul-windows:1.4.0
Applications written in Java Spring Boot.
Problems running the consul from docker-compose using the alpine and linux containers image.
Gateway service is the only registered, the rest of the applications are not registered.
On Windows Server, docker-compose also does not work.
Running on a Windows Server works like this:
<details><summary>Run on Windows Server</summary>
<p>

```bash
# Working only Windows containers

curl -X POST "http://123.123.123.123:2375/v1.39/images/create?fromImage=repos/app1&tag=1.0-SNAPSHOT"
curl -X POST "http://123.123.123.123:2375/v1.39/containers/app1/stop"
curl -X DELETE "http://123.123.123.123:2375/v1.39/containers/app1"
 
curl -H "Content-Type: application/json" -d "{ \"Image\": \"repos/app1:1.0-SNAPSHOT\", \"ExposedPorts\": {\"8083/tcp\": {}},\"Env\":[\"SPRING_CLOUD_CONSUL_HOST=consul\"],\"HostConfig\": {\"PortBindings\": { \"8083/tcp\": [{\"HostPort\": \"8083\"}]}}}" -X POST "http://123.123.123.123:2375/v1.39/containers/create?name=app1"
 
curl -X POST "http://123.123.123.123:2375/v1.39/containers/app1/start"
```

</p>
</details>

*Run on Windows Server* does not work for Linux Containers

I understand that they used a non-official image of the consul.
But when using the problem with registering services, please tell someone what is wrong in the launch or in the application configuration?

<details><summary>My docker-compose.yml</summary>
<p>

```yaml
version: '3.7'

networks:
  app_net:

services:

  consul:
    image: consul:1.4.0 # or used 1.5.2
    container_name: consul
    networks: 
      - app_net
    expose:
      - 8500
    ports:
      - 8500:8500

  gateway:
    image: api-gateway:1.0-SNAPSHOT
    container_name: gateway
    depends_on:
      - consul
    networks: 
      - app_net
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_H2_CONSOLE_ENABLED=true
    expose:
      - 8081
    ports:
      - 8081:8081

  app1:
    image: app1:1.0-SNAPSHOT
    container_name: app1
    depends_on:
      - consul
    networks: 
      - app_net
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_H2_CONSOLE_ENABLED=true
    expose:
      - 8083
    ports:
      - 8083:8083

  app2:
    image: app2:1.0-SNAPSHOT
    container_name: app2
    depends_on:
      - consul
    networks: 
      - app_net
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_H2_CONSOLE_ENABLED=true
    expose:
      - 8092
    ports:
      - 8092:8092
```

</p>
</details>

<details><summary>Use artifacts:</summary>
<p>

```xml
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-consul-discovery</artifactId>
```

</p>
</details>

<details><summary>Gateway application.yml</summary>
<p>

```yaml
spring:
  application:
    name: api-gateway
  cloud:
    consul:
      enabled: true
      host: 0.0.0.0
      port: 8500
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods: "*"
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        locator:
          enabled: true
          predicates:
            - name: Path
              args:
                pattern: "'/api/' + serviceId + '/**'"
          filters:
            - AuthHeaderFilter
            - name: RewritePath
              args:
                regexp: "'/api/' + serviceId + '/(?<remaining>.*)'"
                replacement: "'/${remaining}'"
```

</p>
</details>
<details><summary>App1 and app2 application.yml</summary>
<p>

```yaml
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
      enabled: false
  application:
    name: app1 # or app2
```

</p>
</details>

<details><summary>Consul info</summary>
<p>

```
consul info
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 1
        services = 1
build:
        prerelease =
        revision = 0bddfa23
        version = 1.4.0
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = 127.0.0.1:8300
        server = true
raft:
        applied_index = 21
        commit_index = 21
        fsm_pending = 0
        last_contact = 0
        last_log_index = 21
        last_log_term = 2
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:6f490fb8-89bc-bf8e-7633-05d93e3c4887 Address:127.0.0.1:8300}]
        latest_configuration_index = 1
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 88
        max_procs = 2
        os = linux
        version = go1.11.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 1
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
```

</p>
</details>
<details><summary>Consul service Gateway</summary>
<p>

```json
{"Token":"","Service":{"ID":"api-gateway-8081","Service":"api-gateway","Tags":["secure=false"],"Address":"ae5b8f63b2a7","Meta":null,"Port":8081,"Weights":null,"EnableTagOverride":false,"ProxyDestination":"","Proxy":{},"Connect":{},"CreateIndex":0,"ModifyIndex":0}}
```

</p>
</details>
