### ISSUE TITLE
k8s-sync forwards podIP:port instead of serviceIP:targetPort

### ISSUE THREAD

**Issue by allamand** [hashicorp/consul#6450]
I'm using k8s-sync to access from my k8s service from consul.

my service definition is in the form:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-sync: "true"
  labels:
    app: grafana
    chart: grafana-3.8.5
    heritage: Tiller
    release: prometheus-monitoring
  name: prometheus-monitoring-grafana
  namespace: monitoring
spec:
  clusterIP: 172.31.99.182
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
```

In the consule-UI, I can see that it has configured my service, but it tries to call directly the backend of the service, but on the port the service and not on the targetPort.

in my example, It works If I call manually:
- <service_ip>:<port> or
- <pod_ip>:<targetPort>

But the service configured in consul is calling:
- <pod_ip>:<port> which can't works as my pod don't listen on port.
