### ISSUE TITLE
Duplicate Node IDs on consul 1.5.3

### ISSUE THREAD

**Issue by linydquantil** [hashicorp/consul#7445]
consul version: 1.5.3
i deploy the consul cluster on Kubernetes, i found some projects can't register services
and the server error logs like this:
`2020/03/13 02:07:07 [WARN] consul.fsm: EnsureRegistration failed: failed inserting node: Error while renaming Node ID: "39acce65-162d-c73d-3ec4-c46604d6f0bb": Node name xxx-7556bf9746-bzvjs is reserved by node 7bdbd8e1-859c-f011-038b-0c7423d40294 with name xxx-7556bf9746-bzvjs`

And i also got the agent error logs:
`
2020/03/13 02:09:07 [WARN] agent: Syncing service "portal" failed. rpc error making call: rpc error making call: failed inserting node: Error while renaming Node ID: "39acce65-162d-c73d-3ec4-c46604d6f0bb": Node name xxx-7556bf9746-bzvjs is reserved by node 7bdbd8e1-859c-f011-038b-0c7423d40294 with name xxx-7556bf9746-bzvjs  
2020/03/13 02:09:07 [ERR] agent: failed to sync remote state: rpc error making call: rpc error making call: failed inserting node: Error while renaming Node ID: "39acce65-162d-c73d-3ec4-c46604d6f0bb": Node name xxx-7556bf9746-bzvjs is reserved by node 7bdbd8e1-859c-f011-038b-0c7423d40294 with name xxx-7556bf9746-bzvjs  
2020/03/13 02:09:24 [ERR] consul: "Catalog.Register" RPC failed to server 10.1.0.178:8300: rpc error making call: rpc error making call: failed inserting node: Error while renaming Node ID: "39acce65-162d-c73d-3ec4-c46604d6f0bb": Node name xxx-7556bf9746-bzvjs is reserved by node 7bdbd8e1-859c-f011-038b-0c7423d40294 with name xxx-7556bf9746-bzvjs
`
my consul statefulset yaml like this:

```yaml
containers:
        - name: consul
          image: "consul:1.5.3"
          imagePullPolicy: IfNotPresent
          env:
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GOSSIP_ENCRYPTION_KEY
              value: "xxxx"
            - name: DC
              value: ${dc}
          args:
            - "agent"
            - "-advertise=$(PODIP)"
            - "-bind=0.0.0.0"
            - "-bootstrap-expect=3"
            - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local"
            - "-client=0.0.0.0"
            - "-datacenter=$(DC)"
            - "-data-dir=/consul/data"
            - "-encrypt=$(GOSSIP_ENCRYPTION_KEY)"
            - "-server"
            - "-ui"
            - "-disable-host-node-id"
```
so may i need set disable-host-node-id to false ??
