### ISSUE TITLE
Helm config for ACL token distribution to K8s nodes

### ISSUE THREAD

**Issue by plotia-charter** [hashicorp/consul#7578]
I'm building a hybrid environment with a bare-metal Consul server node and clients who are a part of a K8s cluster. My goal here is to get Mesh Gateway setup. I have reviewed the guides on https://learn.hashicorp.com
I have a single node as consul server (no redundancy setup yet), 3 K8s nodes as clients (1 master & 2 slaves) and a another bare-metal consul server for a second DC. I have WAN joined the two consul server nodes.

While configuring Mesh Gateway, I first need to configure ACL and then ACL replication. I'm working on setting up ACLs right now.

After reading the documentation and doing the configuration, I have still not understood a few concepts. 

1. Does a single helm chart spin-up consul clients on all K8s nodes? My understanding is that it does as the consul members list does show up the K8s nodes.
2. How are ACL node tokens assigned to various K8s nodes via a single helm chart?

Here is my consul server config (it uses 1.7.2):
```
{
  "datacenter": "dc1",
  "primary_datacenter": "dc1",
  "data_dir": "/tmp/consul",
  "log_level": "INFO",
  "node_name": "server1",
  "server": true,
  "connect": {
    "enabled": true,
  },
  "ports": {
    "https": 8501,
    "grpc": 8502
  },
  "bind_addr": "10.0.0.1",
  "client_addr": "10.0.0.1"
  "bootstrap_expect": 1,
  "ui": true,
  "enable_local_script_checks": true
  "acl": {
    "enabled": true,
    "down_policy": "async-cache",
    "default_policy": "deny",
    "enable_token_persistence": true
  }
}
```

Here is the helm config on the K8s master node:
```
global:
  enabled: false

client:
  enabled: true
  image: "consul:1.7.2"
  exposeGossipPorts: true
  join:
    - "10.0.0.1"
  grpc: true

connectInject:
  enabled: true
  default: true
  imageEnvoy: "envoyproxy/envoy-alpine:v1.13.0"
  aclInjectToken:
    secretName: null       //reserved this for service token for ACL
    secretKey: null          //reserved this for service token for ACL
  aclBindingRuleSelector: ""
  centralConfig:
    enabled: true
    defaultProtocol: "tcp"

syncCatalog:
  enabled: true
  default: true
  aclSyncToken:
    secretName: "secret-k8s-master-agent"     //this is where the node ACL token is stored
    secretKey: "secret_k8s_master_agent".        //this is where the node ACL token is stored
  logLevel: "trace"

tests:
  enabled: true
```

Here is my secret definition file which defines token for the K8s master node:
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-k8s-master-agent 
type: Opaque
data:
  secret_k8s_master_agent: <redacted-base64-of-token>
```

How and where do I add ACL node tokens for other K8s nodes which I want as clients?
