### ISSUE TITLE
error converting YAML to JSON: yaml: line 42: did not find expected '-' indicator

### ISSUE THREAD

**Issue by fsckzy** [hashicorp/consul#7825]
k8s 1.17.5
helm 3.2.1
Customizing  Installation error

```shell
[root@k8sm1 opt]# helm install consul hashicorp/consul -f config.yaml
Error: YAML parse error on consul/templates/server-statefulset.yaml: error converting YAML to JSON: yaml: line 42: did not find expected '-' indicato
```
config.yaml
```yaml
global:
  image: 'consul:1.5.0'
  domain: consul
  datacenter: primarydc
  bootstrapACLs: false
server:
  replicas: 3
  bootstrapExpect: 3
  resources: |
    requests:
      memory: "8Gi"
      cpu: "4"
      disk: "5Gi"
    limits:
      memory: "8Gi"
      cpu: "4"
      disk: "5Gi"
  affinity: |
    podAntiAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       - labelSelector:
           matchLabels:
             app: {{ template "consul.name" . }}
             release: "{{ .Release.Name }}"
             component: server
       topologyKey: kubernetes.io/hostname
client:
  resources: |
    requests:
      memory: "2Gi"
      cpu: "2"
      disk: "5Gi"
    limits:
      memory: "2Gi"
      cpu: "2"
      disk: "5Gi"
ui:
  enabled: true
connectInject:
  enabled: true
  default: true
  aclBindingRuleSelector: “serviceaccount.name!=default”
```
please help me
