### ISSUE TITLE
Consul Sidecar - Not Injecting (GKE, Helm)

### ISSUE THREAD

**Issue by kpurdon** [hashicorp/consul#7950]
#### Overview of the Issue

After installing Consul on GKE w/ Helm the connect injector is not adding a sidcar to pods w/ the annotation. I'm obviously missing something, but after reviewing issues, reading documentation, ... I just cannot find anything wrong.

#### Reproduction Steps

1. Create a GKE cluster, and install Consul via helm (values below)
2. Deploy a simple Deployment/Pod (example provided)
3. See nothing in logs, and no sidecar injected

<details>
    <summary>Deployment/Pod</summary>

```
apiVersion: v1
kind: Service
metadata:
  name: ceweb
  labels:
    app: ceweb
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ceweb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceweb
  labels:
    app: ceweb
    cf_build_id: {{CF_BUILD_ID}}
spec:
  replicas: 7
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 75%
  selector:
    matchLabels:
      app.kubernetes.io/name: ceweb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ceweb
        cf_build_id: {{CF_BUILD_ID}}
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: ce-service-account
      containers:
        - name: ceweb
          image: {{IMAGE}}:{{IMAGE_VERSION}}
          resources:
            limits:
              cpu: 2
              memory: 5G
            requests:
              cpu: 1
              memory: 3G
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: FallbackToLogsOnError
          command: ["sh", "-c", "gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS && gunicorn --bind 0.0.0.0:8000 --config gunicorn.conf.py --timeout 120 cv.wsgi"]
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - secretRef:
                name: ce
            - configMapRef:
                name: ce
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
              path: /liveness/
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: http
              path: /readiness/
            periodSeconds: 60
            timeoutSeconds: 10
      nodeSelector:
        role: apps
```

</details>

<details>
    <summary>Helm Values</summary>

```
global:
  image: consul:1.7.3
  datacenter: gcp

  # enable automatic encrypted communication between consul clients and servers
  tls:
    enabled: true
    enableAutoEncrypt: true

  # enable gossip encryption
  # https://www.consul.io/docs/agent/options.html#_encrypt
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key

server:
  # TODO: monitor these and use defaults once they exist
  # https://github.com/hashicorp/consul-helm/issues/393
  resources: |
    limits:
      cpu: 200m
      memory: 250Mi
    requests:
      cpu: 50m
      memory: 100Mi
  # set affinity to the recommended default, even though there isn't an actual default
  # https://www.consul.io/docs/platform/k8s/helm.html#v-server-affinity
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname
client:
  # TODO: monitor these and use defaults once they exist
  # https://github.com/hashicorp/consul-helm/issues/393
  resources: |
    limits:
      cpu: 200m
      memory: 250Mi
    requests:
      cpu: 50m
      memory: 100Mi
# TODO: disabled until we figure out how to guard it w/ authentication (like we do w/ Atlantis)
# https://github.com/hashicorp/consul-helm/issues/433
ui:
  enabled: false

# enable mesh connector injection
# https://learn.hashicorp.com/consul?track=developer-mesh#developer-mesh
connectInject:
  enabled: true
  # require services to opt-in via annotations
  # https://www.consul.io/docs/platform/k8s/connect.html#consul-hashicorp-com-connect-inject
  default: false
```

</details>

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 8b4a3d95
	version = 1.7.3
consul:
	acl = disabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 16
	goroutines = 53
	max_procs = 16
	os = linux
	version = go1.13.7
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 5
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 1
	member_time = 85
	members = 12
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 8b4a3d95
	version = 1.7.3
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.12.3.143:8300
	server = true
raft:
	applied_index = 33708
	commit_index = 33708
	fsm_pending = 0
	last_contact = 42.293153ms
	last_log_index = 33708
	last_log_term = 9
	last_snapshot_index = 32776
	last_snapshot_term = 9
	latest_configuration = [{Suffrage:Voter ID:372100d2-9083-7de2-3d1d-ffddb0912c0a Address:10.12.3.143:8300} {Suffrage:Voter ID:e3bbb10e-6ad9-1ebf-7bff-0ddfd3cf77dc Address:10.12.2.95:8300} {Suffrage:Voter ID:50438c36-ce2d-5072-0e07-bb093b2d2a6f Address:10.12.6.18:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 9
runtime:
	arch = amd64
	cpu_count = 16
	goroutines = 117
	max_procs = 16
	os = linux
	version = go1.13.7
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 5
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 8
	member_time = 85
	members = 19
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 25
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

GKE 1.15.9-gke.24

### Log Fragments

Please LMK if more logs would be useful, just dropped screenshots here since there seemed to be nothing relevant.

#### Injector

<img width="1327" alt="Screen Shot 2020-05-22 at 12 25 58 PM" src="https://user-images.githubusercontent.com/5130441/82698096-6af01d00-9c27-11ea-8e81-baa99d9f27ed.png">

#### Client

<img width="1330" alt="Screen Shot 2020-05-22 at 12 27 26 PM" src="https://user-images.githubusercontent.com/5130441/82698203-9bd05200-9c27-11ea-8a03-9c7ec317ccbb.png">

#### Server

<img width="1332" alt="Screen Shot 2020-05-22 at 12 28 35 PM" src="https://user-images.githubusercontent.com/5130441/82698301-c4f0e280-9c27-11ea-9d13-65bf86cecba7.png">
