### ISSUE TITLE
Multiple private IPv4 addresses found error message even with bind address configured

### ISSUE THREAD

**Issue by jvitorinoj** [hashicorp/consul#8436]
## Overview of the Issue

Run docker consul agent on swarm with CONSUL_BIND_INTERFACE environment variable, consul find the correct IP but still complain about multiple IPv4 addresses

#### Reproduction Steps

1. cat docker-compose.yaml
```
version: '3.6'
services:  
  agent:
    environment:
      CONSUL_BIND_INTERFACE: ens192
    configs:
      - source: consul-config.jsonv5
        target: /etc/config.json
    image: consul:1.8.1
    command: consul agent -config-file=/etc/config.json
    networks:
      - host
    deploy:
      replicas: 1   
configs:
  consul-config.jsonv5:
    external: true
networks:
  host:
    external: true
```

Error:

> ==> Found address '10.19.52.67' for interface 'ens192', setting bind option...
> ==> Multiple private IPv4 addresses found. Please configure one with 'bind' and/or 'advertise'.

2.  Running without swarm mode works fine.
`docker run --net=host -e 'CONSUL_BIND_INTERFACE=ens192' --mount type=bind,source=/opt/config.json,target=/consul/config/config.json consul agent -log-level=TRACE`

### Operating system and Environment details

OS: Oracle Linux Enterprise 7.8
# docker version
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:13:48 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:12:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

# Image 
consul:1.8.0 and consul:1.8.1

### Log Fragments
The consul's agent didn't started, so I didn't catch any log.

**Comment by jsosulska** [comment]
Hello @jvitorinoj ,

Thanks for posting this. In the future, please post questions on our [Discuss Forum](https://discuss.hashicorp.com/c/consul/29) as there will be others who can reply, and provide feedback.

There is not enough information here to troubleshoot. 
- Can you please provide the `config.json` file that is referenced here?
- Can you run the container in swarm, but instead simply sleep the container, SSH in, and see what network interfaces exist?

Best, Jono

**Comment by jvitorinoj** [comment]
The error message said.

` Multiple private IPv4 addresses found. Please configure one with 'bind' AND/OR 'advertise'.`

But only works for me adding bin AND advertise options.
Furthermore, there is the CONSUL_BIND_INTERFACE and CONSUL_CLIENT_INTERFACE variables in the docker image, but the same logic doesn't apply to advertise interface and in the cluster swarm a have servers with different network interfaces names, would be good add a CONSUL_ADVERTISE_INTERFACE variable and the possibility to consider these variables as an array of options.
I will do those changes and then open a PR.

version: '3.6'

```
services:  
  agent:
    environment:
      CONSUL_BIND_INTERFACE: ens192
      CONSUL_CLIENT_INTERFACE: ens192      
    configs:
      - source: consul-config.jsonv5
        target: /consul/config/config.json
    image: consul:1.8.1
    command: consul agent -config-file=/consul/config/config.json -advertise '{{ GetAllInterfaces | include "name" "^ens" | include "flags" "forwardable|up" | attr "address" }}'
...
```
