### ISSUE TITLE
Consul crashed with error "panic: unexpected first node in discovery chain using protocol"

### ISSUE THREAD

**Issue by hudingchen** [hashicorp/consul#8466]
I want to use canary deployment with ingress-gateway, refer to the following sample
https://github.com/nicholasjackson/demo-consul-service-mesh

## Reproduction Steps
+ step-1
```
docker-compose up -d
```

+ step-2 Deploy and start the ingress gateway
```
curl localhost:8500/v1/config -XPUT -d @l7_config/ingress_gateway.json
docker-compose -f docker-compose-ingress.yml up -d
```
+ step-3 deregister payments-1-v1
```
curl --request PUT localhost:8500/v1/agent/service/deregister/payments-1-v1-sidecar-proxy
curl --request PUT localhost:8500/v1/agent/service/deregister/payments-1-v1
docker-compose stop payments_1_v1
```

+ step-4
```
curl localhost:8500/v1/config -XPUT -d @l7_config/payments_service_defaults.json
```
+ step-5
```
curl localhost:8500/v1/config -XPUT -d @l7_config/payments_service_resolver_1.json
```
+ step-6
```
curl localhost:8500/v1/config -XPUT -d @l7_config/payments_service_router_1.json
```
After executing step-6, consul-server crashes with the following error:
```
consul_server_1        | panic: unexpected first node in discovery chain using protocol="tcp": router
consul_server_1        |
consul_server_1        | goroutine 397 [running]:
consul_server_1        | github.com/hashicorp/consul/agent/xds.(*Server).makeUpstreamListenerForDiscoveryChain(0xc000528ea0, 0xc00087b300, 0xc0005fc650, 0x9, 0xc000e00460,                                                                   0xc0005eb180, 0x0, 0x2b75c00, 0x1, 0x15, ...)
consul_server_1        |        /home/circleci/project/consul/agent/xds/listeners.go:780 +0xbab
consul_server_1        | github.com/hashicorp/consul/agent/xds.(*Server).makeIngressGatewayListeners(0xc000528ea0, 0xc0005fc650, 0x9, 0xc0005eb180, 0x1, 0xc000cf6c90, 0x0,                                                                   0x1, 0x0)
consul_server_1        |        /home/circleci/project/consul/agent/xds/listeners.go:301 +0x413
consul_server_1        | github.com/hashicorp/consul/agent/xds.(*Server).listenersFromSnapshotGateway(0xc000528ea0, 0xc0005eb180, 0x0, 0x0, 0xe, 0x1, 0xc0009768c0, 0xc0008                                                                  7b7f0, 0x50bf98)
consul_server_1        |        /home/circleci/project/consul/agent/xds/listeners.go:261 +0x8ee
consul_server_1        | github.com/hashicorp/consul/agent/xds.(*Server).listenersFromSnapshot(0xc000528ea0, 0xc0005eb180, 0x0, 0x0, 0xc0007211a0, 0x3232d6f, 0xe, 0xc0003e                                                                  b3f8, 0xc000721201)
consul_server_1        |        /home/circleci/project/consul/agent/xds/listeners.go:49 +0x291
consul_server_1        | github.com/hashicorp/consul/agent/xds.(*xDSType).SendIfNew(0xc0000a1630, 0xc0005eb180, 0x6, 0xc00087b930, 0xc00087bb50, 0x0)
consul_server_1        |        /home/circleci/project/consul/agent/xds/server.go:408 +0xaf
consul_server_1        | github.com/hashicorp/consul/agent/xds.(*Server).process(0xc000528ea0, 0x388dc00, 0xc0005a7de0, 0xc0007a7e60, 0x0, 0x0)
consul_server_1        |        /home/circleci/project/consul/agent/xds/server.go:369 +0x832
consul_server_1        | github.com/hashicorp/consul/agent/xds.(*Server).StreamAggregatedResources(0xc000528ea0, 0x388dc00, 0xc0005a7de0, 0x382c680, 0xc000528ea0)
consul_server_1        |        /home/circleci/project/consul/agent/xds/server.go:171 +0xc5
consul_server_1        | github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x319c3e0, 0xc0005                                                                  28ea0, 0x3883a60, 0xc0009eac00, 0x54519f8, 0xc0005afc00)
consul_server_1        |        /go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.8.0/envoy/service/discovery/v2/ads.pb.go:197 +0xad
consul_server_1        | google.golang.org/grpc.(*Server).processStreamingRPC(0xc0002a06e0, 0x3893e40, 0xc00054e300, 0xc0005afc00, 0xc0005aa060, 0x53f0360, 0x0, 0x0, 0x0)
consul_server_1        |        /go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1199 +0xd21
consul_server_1        | google.golang.org/grpc.(*Server).handleStream(0xc0002a06e0, 0x3893e40, 0xc00054e300, 0xc0005afc00, 0x0)
consul_server_1        |        /go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1279 +0xcd6
consul_server_1        | google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000718d00, 0xc0002a06e0, 0x3893e40, 0xc00054e300, 0xc0005afc00)
consul_server_1        |        /go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0xa1
consul_server_1        | created by google.golang.org/grpc.(*Server).serveStreams.func1
consul_server_1        |        /go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xa1
```

##  Operating system and Environment details
OS: Centos 7.7
consul: 1.8.0
docker: 19.03.5
docker-compose: 1.25.0

## my config

docker-compose.yml
```
version: "3.3"
services:

  consul_server_1:
    image: nexus.xxx.proxy:8442/consul:1.8.0
    container_name: consul_server_1
    command: ["consul","agent", "-server", "-bootstrap", "-config-file=/config/consul-single-dc.hcl","-config-dir=/config"]
    volumes:
      - "./consul_config:/config"
    ports:
      - "8500:8500"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  payments_1_v1:
    image: nexus.xxx.proxy:8442/nicholasjackson/fake-service:v0.7.8
    container_name: payments_1_v1
    environment:
      NAME: payments-1-v1
      MESSAGE: "PAYMENTS 1 V1"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  payments_1_proxy_v1:
    image: nexus.xxx.proxy:8442/nicholasjackson/consul-envoy:v1.8.0-v1.14.2
    container_name: payments_1_proxy_v1
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/payments_1_v1.hcl
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "payments-1-v1"]
    network_mode: "service:payments_1_v1"

  payments_2_v1:
    image: nexus.xxx.proxy:8442/nicholasjackson/fake-service:v0.7.8
    container_name: payments_2_v1
    environment:
      NAME: payments-2-v1
      MESSAGE: "PAYMENTS 2 V1"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  payments_2_proxy_v1:
    image: nexus.xxx.proxy:8442/nicholasjackson/consul-envoy:v1.8.0-v1.14.2
    container_name: payments_2_proxy_v1
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/payments_2_v1.hcl
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "payments-2-v1"]
    network_mode: "service:payments_2_v1"

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
```

ingress_gateway.json
```
{
    "kind": "ingress-gateway",
    "name": "ingress-service",
    "listeners": [
        {
            "port": 8080,
            "protocol": "tcp",
            "services": [
                {
                    "name": "payments"
                }
            ]
        }
    ]
}
```

docker-compose-ingress.yml
```
version: "3.3"
services:

  ingress_proxy:
    image: nexus.xxx.proxy:8442/nicholasjackson/consul-envoy:v1.8.0-v1.14.2
    container_name: ingress_proxy
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      #      CENTRAL_CONFIG: "/central_config/api_service_defaults.hcl"
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    ports:
      - "8080:8080"
      - "9092:8888"
    command: consul connect envoy -gateway=ingress -register -service ingress-service -address 10.5.0.10:8888

    networks:
      vpcbr:
        ipv4_address: 10.5.0.10

networks:
  vpcbr:
    external:
      name: service-mesh-sample_vpcbr
```

payments_service_defaults.json
```
{
    "kind": "service-defaults",
    "name": "payments",
    "protocol": "http"
}
```

payments_service_resolver_1.json
```
{
    "kind": "service-resolver",
    "name": "payments",
    "default_subset": "v1",
    "subsets": {
        "v1": {
            "filter": "Service.Meta.version == 1"
        },
        "v2": {
            "filter": "Service.Meta.version == 2"
        },
        "payments-1-v2": {
            "filter": "Service.Meta.sid == 1 and Service.Meta.version == 2"
        }
    }
}
```

payments_service_router_1.json
```
{
    "kind": "service-router",
    "name": "payments",
    "routes": [
      {
        "match": {
            "http": {
                "header": [
                    {
                    "name": "testgroup",
                    "exact": "b"
                    }
                ]
          }
        },
        "destination": {
            "service": "payments",
            "service_subset": "payments-1-v2"
        }
      },
      {
        "match": {
            "http": {
                "path_prefix": "/"
          }
        },
    
        "destination": {
            "service": "payments",
            "service_subset": "v1"
        }
      }
    ]
}
```
