### ISSUE TITLE
Setting service-router NumRetries to 0 has no effect

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#8516]
#### Overview of the Issue

Setting `num_retries` to 0 results in envoy still retrying.

```
kind = "service-router"
name = "api"
routes = [
  {
    destination = {
      num_retries = 0,
      retry_on_status_codes = [500]
    }
  }
]
```

Results in:
```
          "route": {
           "cluster": "api.default.gke.internal.a8e6e9ad-c56f-3df4-f08d-f923570c4ca3.consul",
           "retry_policy": {
            "retry_on": "retriable-status-codes",
            "retriable_status_codes": [
             500
            ]
           }
          }
```

If `num_retries = 3` you get:
```
"route": {
           "cluster": "api.default.gke.internal.a8e6e9ad-c56f-3df4-f08d-f923570c4ca3.consul",
           "retry_policy": {
            "retry_on": "retriable-status-codes",
            "num_retries": 3,
            "retriable_status_codes": [
             500
            ]
           }
          }
```

I think because we never set `num_retries: 0` then envoy uses its default of 1 (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-retrypolicy).

If we set `retry_on_status_codes = []` then we get no retries because the retry_policy block is omitted from the envoy config:
```
 "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "api.default.gke.internal.a8e6e9ad-c56f-3df4-f08d-f923570c4ca3.consul"
          }
         },
```

### Consul version
`1.8.2`

**Comment by Mouni919** [comment]
Hi @lkysow

I would like to update Envoy to disable its automatic retry on request failure (for every back-end services). Im updating this  in values.yaml file 

```
routesOnly:
  # Launcher Mgmt Streaming status
  - name: launcher-mgmt-ms
    ports: 
      servicePort: 9100
      containerPort: 9100
    rewrite:
      uri: /
    route:
      prefix: /launcher/streaming/
      retry_on_status_codes: []
      timeoutSeconds: 300
     
  # Lesson Mgmt Health
  - name: lesson-mgmt-ms
    ports: 
      servicePort: 8300
      containerPort: 8300
    rewrite:
      uri: /status/
    route:
      prefix: /rest/api/latest/lesson/status/
      retry_on_status_codes: []
      timeoutSeconds: 300
 ```

Is that above entry of "retry_on_status_codes: []" in the 2 services correct or you want me to update it anywhere else?
Can you please have a look at it once and confirm?

Thanks.

**Comment by Amier3** [comment]
Hey @Mouni919 

This issue is referring to the `numretries`associated with services connected to a `ServiceRouter`, so the `retry_on_status_codes` parameter would need to be set in the yaml file for each router: 

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: api
spec:
  routes:
      - destination:
           num_retries=0
           retry_on_status_codes: []
```

If you're trying to disable retries for all requests and not just within a service router, I would suggest asking in our forum [discuss.hashicorp.com ](discuss.hashicorp.com) . We try to keep our github for feature requests and bug reports 😅
